const fs = require('fs');
const raw = fs.readFileSync('match_engine/webapp/public/style.css', 'utf8');
const lines = raw.split('\n');

const KEEP_BEFORE = lines.slice(0, 3720);
const KEEP_AFTER  = lines.slice(4143);

// Build the new wizard section using design tokens
const NEW_WIZARD_LINES = [
`/* ==========================================================`,
`   TOURNAMENT \u2014 Wizard  (design tokens)`,
`========================================================== */`,
`#main-trn-wrap {`,
`  max-width: 640px;`,
`  margin: 0 auto;`,
`  padding: 0 1rem 4rem;`,
`}`,
``,
`/* -- Step bar */`,
`.trn-stepbar {`,
`  display: flex;`,
`  align-items: center;`,
`  justify-content: center;`,
`  padding: 1.6rem 0 1rem;`,
`}`,
`.trn-stepbar-item {`,
`  display: flex;`,
`  flex-direction: column;`,
`  align-items: center;`,
`  gap: .3rem;`,
`}`,
`.trn-stepbar-num {`,
`  width: 34px; height: 34px;`,
`  border-radius: 50%;`,
`  border: 2px solid var(--border);`,
`  background: var(--bg-card);`,
`  display: flex; align-items: center; justify-content: center;`,
`  font: 700 .82rem/1 var(--font);`,
`  color: var(--grey);`,
`  transition: border-color .22s, background .22s, color .22s, box-shadow .22s;`,
`}`,
`.trn-stepbar-label {`,
`  font: 600 .65rem/1 var(--font);`,
`  color: var(--grey);`,
`  letter-spacing: .08em;`,
`  text-transform: uppercase;`,
`  transition: color .22s;`,
`}`,
`.trn-stepbar-active .trn-stepbar-num {`,
`  border-color: var(--neon);`,
`  background: rgba(0,212,255,.1);`,
`  color: var(--neon);`,
`  box-shadow: 0 0 14px rgba(0,212,255,.25);`,
`}`,
`.trn-stepbar-active .trn-stepbar-label { color: var(--neon); }`,
`.trn-stepbar-done .trn-stepbar-num {`,
`  border-color: rgba(0,212,255,.4);`,
`  background: rgba(0,212,255,.07);`,
`  color: rgba(0,212,255,.65);`,
`}`,
`.trn-stepbar-done .trn-stepbar-label { color: rgba(0,212,255,.45); }`,
`.trn-stepbar-line {`,
`  width: 52px; height: 2px;`,
`  background: var(--border);`,
`  margin: 0 4px 1.1rem;`,
`  flex-shrink: 0;`,
`  transition: background .22s;`,
`}`,
`.trn-stepbar-line-done { background: rgba(0,212,255,.4); }`,
``,
`/* -- Step container */`,
`.trn-step { animation: trnFadeUp .22s ease both; }`,
`.trn-step-header {`,
`  display: flex;`,
`  align-items: baseline;`,
`  justify-content: space-between;`,
`  flex-wrap: wrap;`,
`  gap: .4rem;`,
`  padding-bottom: 1rem;`,
`  border-bottom: 1px solid var(--border);`,
`  margin-bottom: 1.3rem;`,
`}`,
`.trn-step-title {`,
`  font: 700 1.45rem/1 var(--font);`,
`  color: var(--white);`,
`  letter-spacing: .01em;`,
`  margin: 0;`,
`}`,
`.trn-step-hint {`,
`  font-size: .82rem;`,
`  color: var(--grey);`,
`  width: 100%;`,
`  margin: .25rem 0 0;`,
`}`,
``,
`/* -- Format cards */`,
`.trn-fmt-grid {`,
`  display: flex;`,
`  flex-direction: column;`,
`  gap: .5rem;`,
`  margin-bottom: 1.2rem;`,
`}`,
`.trn-fmt-card {`,
`  display: flex;`,
`  align-items: center;`,
`  gap: 1rem;`,
`  background: var(--bg-card);`,
`  border: 1px solid var(--border);`,
`  border-radius: var(--radius-md);`,
`  padding: .9rem 1rem;`,
`  cursor: pointer;`,
`  text-align: left;`,
`  color: inherit;`,
`  width: 100%;`,
`  transition: border-color .18s, background .18s;`,
`  position: relative;`,
`}`,
`.trn-fmt-card:hover {`,
`  background: rgba(255,255,255,.06);`,
`  border-color: rgba(0,212,255,.3);`,
`}`,
`.trn-fmt-selected {`,
`  border-color: rgba(0,212,255,.6) !important;`,
`  background: rgba(0,212,255,.06) !important;`,
`  box-shadow: 0 0 0 1px rgba(0,212,255,.15);`,
`}`,
`.trn-fmt-visual {`,
`  font-size: 1.6rem;`,
`  width: 2.2rem;`,
`  text-align: center;`,
`  flex-shrink: 0;`,
`  line-height: 1;`,
`}`,
`.trn-fmt-info { flex: 1; min-width: 0; }`,
`.trn-fmt-name {`,
`  font: 600 1rem/1 var(--font);`,
`  color: var(--white);`,
`  margin-bottom: .2rem;`,
`}`,
`.trn-fmt-desc {`,
`  font-size: .77rem;`,
`  color: var(--grey);`,
`  margin-bottom: .32rem;`,
`}`,
`.trn-fmt-tags { display: flex; gap: .35rem; flex-wrap: wrap; }`,
`.trn-fmt-tags span {`,
`  font: 600 .65rem/1 var(--font);`,
`  letter-spacing: .06em;`,
`  text-transform: uppercase;`,
`  color: var(--grey);`,
`  background: rgba(255,255,255,.05);`,
`  border: 1px solid var(--border);`,
`  border-radius: 99px;`,
`  padding: .14rem .5rem;`,
`}`,
`.trn-fmt-selected .trn-fmt-tags span {`,
`  color: var(--neon);`,
`  background: rgba(0,212,255,.08);`,
`  border-color: rgba(0,212,255,.3);`,
`}`,
`.trn-fmt-check {`,
`  font-size: 1rem;`,
`  color: transparent;`,
`  transition: color .18s;`,
`  flex-shrink: 0;`,
`  font-weight: 700;`,
`  width: 1.4rem;`,
`  text-align: center;`,
`}`,
`.trn-fmt-selected .trn-fmt-check { color: var(--neon); }`,
``,
`.trn-num-teams-row {`,
`  display: flex;`,
`  align-items: center;`,
`  gap: .85rem;`,
`  padding: .75rem 0 0;`,
`  border-top: 1px solid var(--border);`,
`}`,
`.trn-label {`,
`  font: 600 .75rem/1 var(--font);`,
`  color: var(--grey);`,
`  letter-spacing: .08em;`,
`  text-transform: uppercase;`,
`  flex-shrink: 0;`,
`}`,
`.trn-select { width: auto; min-width: 130px; }`,
``,
`/* -- Rules toggles */`,
`.trn-rules-list {`,
`  display: flex;`,
`  flex-direction: column;`,
`  gap: .5rem;`,
`  margin-bottom: 1.2rem;`,
`}`,
`.trn-rule-row {`,
`  display: flex;`,
`  align-items: center;`,
`  justify-content: space-between;`,
`  gap: .9rem;`,
`  cursor: pointer;`,
`  padding: .85rem 1rem;`,
`  background: var(--bg-card);`,
`  border: 1px solid var(--border);`,
`  border-radius: var(--radius-md);`,
`  transition: background .14s, border-color .14s;`,
`}`,
`.trn-rule-row:hover {`,
`  background: rgba(255,255,255,.06);`,
`  border-color: rgba(0,212,255,.25);`,
`}`,
`.trn-rule-body { flex: 1; min-width: 0; }`,
`.trn-rule-name {`,
`  display: block;`,
`  font: 600 .92rem/1 var(--font);`,
`  color: var(--white);`,
`  margin-bottom: .22rem;`,
`}`,
`.trn-rule-hint {`,
`  display: block;`,
`  font-size: .74rem;`,
`  color: var(--grey);`,
`}`,
`.trn-toggle-wrap { position: relative; flex-shrink: 0; }`,
`.trn-toggle-input { position: absolute; opacity: 0; width: 0; height: 0; }`,
`.trn-toggle {`,
`  display: block;`,
`  width: 42px; height: 24px;`,
`  background: rgba(255,255,255,.1);`,
`  border-radius: 999px;`,
`  position: relative;`,
`  transition: background .2s;`,
`  cursor: pointer;`,
`}`,
`.trn-toggle::after {`,
`  content: '';`,
`  position: absolute;`,
`  top: 3px; left: 3px;`,
`  width: 18px; height: 18px;`,
`  border-radius: 50%;`,
`  background: rgba(255,255,255,.45);`,
`  transition: transform .2s, background .2s;`,
`}`,
`.trn-toggle-input:checked + .trn-toggle { background: rgba(0,212,255,.65); }`,
`.trn-toggle-input:checked + .trn-toggle::after {`,
`  transform: translateX(18px);`,
`  background: #fff;`,
`}`,
``,
`/* -- Step actions */`,
`.trn-step-actions {`,
`  display: flex;`,
`  gap: .55rem;`,
`  margin-top: 1.2rem;`,
`  flex-wrap: wrap;`,
`}`,
`.trn-btn-next   { padding: .65rem 2rem; }`,
`.trn-btn-simulate { flex: 1; min-width: 160px; padding: .7rem 1rem; font-size: .95rem; }`,
``,
`/* -- Team search */`,
`.trn-search-wrap { position: relative; margin-bottom: .85rem; }`,
`.trn-search-field-wrap {`,
`  display: flex;`,
`  align-items: center;`,
`  background: rgba(255,255,255,.05);`,
`  border: 1px solid var(--border);`,
`  border-radius: var(--radius-md);`,
`  padding: .65rem 1rem;`,
`  gap: .6rem;`,
`  transition: border-color .15s, box-shadow .15s;`,
`}`,
`.trn-search-field-wrap:focus-within {`,
`  border-color: var(--neon);`,
`  box-shadow: 0 0 0 3px rgba(0,212,255,.12);`,
`}`,
`.trn-search-icon-prefix { font-size: .95rem; flex-shrink: 0; line-height: 1; opacity: .5; }`,
`.trn-search-field-wrap input {`,
`  flex: 1;`,
`  background: none;`,
`  border: none;`,
`  outline: none;`,
`  color: var(--white);`,
`  font: 500 .95rem/1 var(--font);`,
`  min-width: 0;`,
`}`,
`.trn-search-field-wrap input::placeholder { color: var(--grey); }`,
`.trn-search-clear {`,
`  background: none; border: none; cursor: pointer;`,
`  color: var(--grey); font-size: .85rem;`,
`  padding: .1rem .2rem; line-height: 1; flex-shrink: 0;`,
`  transition: color .12s;`,
`}`,
`.trn-search-clear:hover { color: var(--accent-b); }`,
`.trn-search-results {`,
`  position: absolute;`,
`  top: calc(100% + 4px);`,
`  left: 0; right: 0;`,
`  background: #0d1525;`,
`  border: 1px solid rgba(0,212,255,.2);`,
`  border-radius: var(--radius-md);`,
`  z-index: 50;`,
`  max-height: 230px;`,
`  overflow-y: auto;`,
`  box-shadow: var(--shadow);`,
`}`,
`.trn-search-item {`,
`  display: flex;`,
`  align-items: center;`,
`  gap: .7rem;`,
`  padding: .62rem 1rem;`,
`  cursor: pointer;`,
`  border-bottom: 1px solid var(--border);`,
`  transition: background .1s;`,
`}`,
`.trn-search-item:last-child { border-bottom: none; }`,
`.trn-search-item:hover { background: rgba(0,212,255,.08); }`,
`.trn-search-item-name {`,
`  font: 500 .9rem/1 var(--font);`,
`  color: var(--white);`,
`  flex: 1;`,
`}`,
`.trn-search-item-meta {`,
`  font-size: .72rem;`,
`  color: var(--grey);`,
`  flex-shrink: 0;`,
`}`,
`.trn-search-empty {`,
`  padding: .8rem 1rem;`,
`  font-size: .84rem;`,
`  color: var(--grey);`,
`}`,
``,
`/* -- Teams header row */`,
`.trn-teams-header {`,
`  display: flex;`,
`  align-items: center;`,
`  justify-content: space-between;`,
`  gap: .6rem;`,
`  margin-bottom: .55rem;`,
`}`,
`.trn-progress-row {`,
`  display: flex;`,
`  align-items: center;`,
`  gap: .4rem;`,
`  flex-shrink: 0;`,
`}`,
`.trn-count-num {`,
`  font: 700 1.35rem/1 var(--font);`,
`  color: var(--neon);`,
`  min-width: 1.5rem;`,
`  text-align: right;`,
`}`,
`.trn-count-sep { font: 700 1rem/1 var(--font); color: var(--grey); }`,
`.trn-count-total { font: 600 .92rem/1 var(--font); color: var(--grey); }`,
`.trn-count-bar {`,
`  width: 64px; height: 4px;`,
`  background: var(--border);`,
`  border-radius: 99px;`,
`  overflow: hidden;`,
`  margin-left: .35rem;`,
`}`,
`.trn-count-fill {`,
`  height: 100%;`,
`  background: linear-gradient(90deg, var(--neon), var(--neon2));`,
`  border-radius: 99px;`,
`  width: 0%;`,
`  transition: width .3s ease;`,
`}`,
``,
`/* -- Team slots */`,
`.trn-teams-list {`,
`  display: grid;`,
`  grid-template-columns: repeat(2, 1fr);`,
`  gap: .4rem;`,
`  margin-bottom: .85rem;`,
`  max-height: 250px;`,
`  overflow-y: auto;`,
`}`,
`.trn-team-slot {`,
`  display: flex;`,
`  align-items: center;`,
`  justify-content: space-between;`,
`  background: var(--bg-card);`,
`  border: 1px solid var(--border);`,
`  border-radius: var(--radius-sm);`,
`  padding: .45rem .75rem;`,
`  gap: .4rem;`,
`  min-width: 0;`,
`  animation: trnFadeUp .15s ease both;`,
`}`,
`.trn-slot-name {`,
`  font: 500 .83rem/1.2 var(--font);`,
`  color: var(--white);`,
`  white-space: nowrap;`,
`  overflow: hidden;`,
`  text-overflow: ellipsis;`,
`  flex: 1;`,
`  min-width: 0;`,
`}`,
`.trn-slot-era { font-size: .7rem; color: var(--grey); }`,
`.trn-slot-remove {`,
`  background: none; border: none; cursor: pointer;`,
`  color: var(--grey); font-size: .78rem;`,
`  padding: .1rem .25rem; transition: color .12s; flex-shrink: 0;`,
`}`,
`.trn-slot-remove:hover { color: var(--accent-b); }`,
`.trn-teams-empty {`,
`  grid-column: 1 / -1;`,
`  text-align: center;`,
`  padding: 1.8rem 0;`,
`  font-size: .84rem;`,
`  color: var(--grey);`,
`}`,
``,
`/* -- Progress / loading */`,
`.trn-progress {`,
`  display: flex;`,
`  align-items: center;`,
`  gap: .85rem;`,
`  padding: 1.1rem .2rem .3rem;`,
`  font-size: .88rem;`,
`  color: var(--neon);`,
`}`,
`.trn-spinner {`,
`  width: 22px; height: 22px;`,
`  border: 2.5px solid rgba(0,212,255,.15);`,
`  border-top-color: var(--neon);`,
`  border-radius: 50%;`,
`  animation: spin .65s linear infinite;`,
`  flex-shrink: 0;`,
`}`,
`@keyframes spin { to { transform: rotate(360deg); } }`,
];

const result = [...KEEP_BEFORE, ...NEW_WIZARD_LINES, ...KEEP_AFTER].join('\n');
fs.writeFileSync('match_engine/webapp/public/style.css', result);
const written = fs.readFileSync('match_engine/webapp/public/style.css', 'utf8');
console.log('Written. Lines:', written.split('\n').length);
const greenCount = (written.match(/rgba\(0,200,120/g) || []).length;
console.log('Remaining rgba(0,200,120) references:', greenCount);
const neonCount = (written.match(/var\(--neon\)/g) || []).length;
console.log('var(--neon) occurrences total:', neonCount);
