@echo off
echo ============================================
echo  Git Setup for Victor Vega - Ultra KibanaDownloader
echo ============================================

echo [INFO] Checking if Git is already installed...
git --version >nul 2>&1
if %errorlevel% equ 0 (
    echo [OK] Git is already installed!
    git --version
    goto :setup_repo
)

echo [INFO] Git not found. Installing Git for Windows...
echo [INFO] Downloading Git installer...

powershell -Command "& {Invoke-WebRequest -Uri 'https://github.com/git-for-windows/git/releases/download/v2.42.0.windows.2/Git-2.42.0.2-64-bit.exe' -OutFile 'Git-Installer.exe'}"

if exist "Git-Installer.exe" (
    echo [INFO] Running Git installer...
    echo [NOTE] Please follow the installation wizard
    echo [NOTE] Keep default settings, just click "Next" and "Install"
    start /wait Git-Installer.exe
    
    echo [INFO] Cleaning up installer...
    del Git-Installer.exe
    
    echo [INFO] Please close and reopen your terminal, then run this script again
    pause
    exit
) else (
    echo [ERROR] Failed to download Git installer
    echo [INFO] Please download Git manually from: https://git-scm.com/download/win
    pause
    exit
)

:setup_repo
echo.
echo ============================================
echo  Setting up Git Repository for Victor Vega
echo ============================================

echo [INFO] Configuring Git with your Verisure information...
git config --global user.name "Victor Vega"
git config --global user.email "victor.vega@verisure.com"

echo [INFO] Initializing Git repository...
git init

echo [INFO] Creating .gitignore file...
echo # Ultra KibanaDownloader - Git Ignore Rules > .gitignore
echo # Generated by Victor Vega for Verisure >> .gitignore
echo. >> .gitignore
echo # Compiled class files >> .gitignore
echo *.class >> .gitignore
echo. >> .gitignore
echo # Package files >> .gitignore
echo *.jar >> .gitignore
echo !ElasticLoganaGUI.jar >> .gitignore
echo. >> .gitignore
echo # Log files >> .gitignore
echo logs/*.log >> .gitignore
echo logs/*.txt >> .gitignore
echo. >> .gitignore
echo # Temporary files >> .gitignore
echo *.tmp >> .gitignore
echo *.temp >> .gitignore
echo. >> .gitignore
echo # ZIP distribution files >> .gitignore
echo Ultra-KibanaDownloader-*.zip >> .gitignore
echo. >> .gitignore
echo # IDE files >> .gitignore
echo .vscode/ >> .gitignore
echo .idea/ >> .gitignore
echo *.iml >> .gitignore
echo. >> .gitignore
echo # Python cache >> .gitignore
echo __pycache__/ >> .gitignore
echo *.pyc >> .gitignore

echo [INFO] Adding files to Git...
git add .

echo [INFO] Creating initial commit...
git commit -m "Initial commit: Ultra KibanaDownloader v1.0 by Victor Vega - Professional log analytics tool for Verisure"

echo.
echo ============================================
echo  NEXT STEPS FOR VICTOR:
echo ============================================
echo.
echo 1. CREATE GITHUB REPOSITORY:
echo    - Go to: https://github.com
echo    - Login with: victor-vega_vsure (or create account)
echo    - Click "New repository" (green button)
echo    - Repository name: ultra-kibana-downloader
echo    - Description: "Advanced log analytics tool for Elasticsearch - Verisure"
echo    - Choose: Public (recommended) or Private
echo    - DON'T check "Add a README file"
echo    - Click "Create repository"
echo.
echo 2. CONNECT TO GITHUB:
echo    After creating the repository, run these commands:
echo.
echo    git remote add origin https://github.com/victor-vega_vsure/ultra-kibana-downloader.git
echo    git branch -M main
echo    git push -u origin main
echo.
echo 3. SHARE WITH TEAM:
echo    Repository URL will be:
echo    https://github.com/victor-vega_vsure/ultra-kibana-downloader
echo.
echo ============================================
echo  DAILY WORKFLOW FOR VICTOR:
echo ============================================
echo.
echo After making changes to your code:
echo.
echo git add .
echo git commit -m "Description of changes"
echo git push
echo.
echo Example:
echo git commit -m "Added new modern dialog for service selection"
echo git commit -m "Fixed progress bar issue"
echo git commit -m "Updated documentation"
echo git commit -m "Released version 1.1"
echo.
echo ============================================
echo  REPOSITORY READY!
echo ============================================
echo.
echo Your Ultra KibanaDownloader is now:
echo ✅ Git repository initialized
echo ✅ Configured for Victor Vega at Verisure
echo ✅ Initial commit created
echo ✅ Ready to push to GitHub
echo.
echo Go create your GitHub repository and then run the connection commands above!
echo.
pause
