'use strict';
/**
 * _fill_wc_seasons.js
 * Adds missing historical World Cup seasons to squad JSON files.
 * Run: node _fill_wc_seasons.js
 */
const fs = require('fs');
const path = require('path');

// ─── SEASON STUBS — keyed as "slug:year" ──────────────────────────────────
// Each entry: { formation, teamLabel, source, ratings, players[11] }
const STUBS = {

  // ── ENGLAND ──────────────────────────────────────────────────────────
  'england:1966': {
    formation: '4-4-2', teamLabel: 'England (1966)',
    source: 'England - World Cup 1966 (Champions)',
    ratings: { attack: 87, midfield: 84, defense: 85, goalkeeping: 86 },
    players: [
      { name: 'Gordon Banks',      position: 'GK', rating: 87 },
      { name: 'George Cohen',      position: 'RB', rating: 82 },
      { name: 'Bobby Moore',       position: 'CB', rating: 90 },
      { name: 'Jack Charlton',     position: 'CB', rating: 84 },
      { name: 'Ray Wilson',        position: 'LB', rating: 82 },
      { name: 'Alan Ball',         position: 'CM', rating: 84 },
      { name: 'Nobby Stiles',      position: 'DM', rating: 82 },
      { name: 'Bobby Charlton',    position: 'CM', rating: 90 },
      { name: 'Martin Peters',     position: 'AM', rating: 84 },
      { name: 'Geoff Hurst',       position: 'ST', rating: 88 },
      { name: 'Roger Hunt',        position: 'ST', rating: 82 },
    ],
  },
  'england:1970': {
    formation: '4-4-2', teamLabel: 'England (1970)',
    source: 'England - World Cup 1970',
    ratings: { attack: 84, midfield: 83, defense: 83, goalkeeping: 86 },
    players: [
      { name: 'Gordon Banks',      position: 'GK', rating: 87 },
      { name: 'Keith Newton',      position: 'RB', rating: 80 },
      { name: 'Bobby Moore',       position: 'CB', rating: 89 },
      { name: 'Brian Labone',      position: 'CB', rating: 82 },
      { name: 'Terry Cooper',      position: 'LB', rating: 81 },
      { name: 'Alan Mullery',      position: 'DM', rating: 81 },
      { name: 'Bobby Charlton',    position: 'CM', rating: 87 },
      { name: 'Alan Ball',         position: 'CM', rating: 83 },
      { name: 'Martin Peters',     position: 'AM', rating: 83 },
      { name: 'Geoff Hurst',       position: 'ST', rating: 85 },
      { name: 'Francis Lee',       position: 'ST', rating: 81 },
    ],
  },
  'england:1982': {
    formation: '4-4-2', teamLabel: 'England (1982)',
    source: 'England - World Cup 1982',
    ratings: { attack: 79, midfield: 79, defense: 80, goalkeeping: 80 },
    players: [
      { name: 'Peter Shilton',     position: 'GK', rating: 81 },
      { name: 'Mick Mills',        position: 'RB', rating: 77 },
      { name: 'Terry Butcher',     position: 'CB', rating: 80 },
      { name: 'Phil Thompson',     position: 'CB', rating: 79 },
      { name: 'Kenny Sansom',      position: 'LB', rating: 79 },
      { name: 'Ray Wilkins',       position: 'CM', rating: 80 },
      { name: 'Bryan Robson',      position: 'CM', rating: 85 },
      { name: 'Glenn Hoddle',      position: 'AM', rating: 83 },
      { name: 'Trevor Francis',    position: 'RW', rating: 80 },
      { name: 'Paul Mariner',      position: 'ST', rating: 79 },
      { name: 'Kevin Keegan',      position: 'ST', rating: 82 },
    ],
  },
  'england:1990': {
    formation: '4-4-2', teamLabel: 'England (1990)',
    source: 'England - World Cup 1990 (Semi-finals)',
    ratings: { attack: 81, midfield: 82, defense: 81, goalkeeping: 82 },
    players: [
      { name: 'Peter Shilton',     position: 'GK', rating: 83 },
      { name: 'Paul Parker',       position: 'RB', rating: 78 },
      { name: 'Terry Butcher',     position: 'CB', rating: 80 },
      { name: 'Des Walker',        position: 'CB', rating: 82 },
      { name: 'Stuart Pearce',     position: 'LB', rating: 83 },
      { name: 'Bryan Robson',      position: 'CM', rating: 82 },
      { name: 'Paul Gascoigne',    position: 'CM', rating: 87 },
      { name: 'Chris Waddle',      position: 'RW', rating: 82 },
      { name: 'Peter Beardsley',   position: 'AM', rating: 83 },
      { name: 'Gary Lineker',      position: 'ST', rating: 87 },
      { name: 'John Barnes',       position: 'LW', rating: 82 },
    ],
  },

  // ── MÉXICO ───────────────────────────────────────────────────────────
  'mexiko:1970': {
    formation: '4-4-2', teamLabel: 'México (1970)',
    source: 'México - World Cup 1970 (host)',
    ratings: { attack: 76, midfield: 74, defense: 73, goalkeeping: 72 },
    players: [
      { name: 'Ignacio Calderón',  position: 'GK', rating: 73 },
      { name: 'Gustavo Peña',      position: 'RB', rating: 73 },
      { name: 'Mario Pérez',       position: 'CB', rating: 73 },
      { name: 'Javier López',      position: 'CB', rating: 72 },
      { name: 'Rafael Ramos',      position: 'LB', rating: 72 },
      { name: 'Rubén Reyes',       position: 'CM', rating: 74 },
      { name: 'Horacio López',     position: 'DM', rating: 73 },
      { name: 'Salvador Reyes',    position: 'CM', rating: 74 },
      { name: 'Enrique Borja',     position: 'AM', rating: 77 },
      { name: 'Javier Fragoso',    position: 'ST', rating: 75 },
      { name: 'Pedro Flores',      position: 'LW', rating: 74 },
    ],
  },
  'mexiko:1986': {
    formation: '4-3-3', teamLabel: 'México (1986)',
    source: 'México - World Cup 1986 (host, QF)',
    ratings: { attack: 79, midfield: 77, defense: 76, goalkeeping: 77 },
    players: [
      { name: 'Pablo Larios',      position: 'GK', rating: 77 },
      { name: 'Félix Cruz',        position: 'RB', rating: 75 },
      { name: 'Manuel Negrete',    position: 'CB', rating: 76 },
      { name: 'Servando Borreguero', position: 'CB', rating: 75 },
      { name: 'Agustín Manzo',     position: 'LB', rating: 74 },
      { name: 'Javier Aguirre',    position: 'DM', rating: 77 },
      { name: 'Tomás Boy',         position: 'CM', rating: 77 },
      { name: 'Carlos de los Cobos', position: 'CM', rating: 76 },
      { name: 'Luis Flores',       position: 'RW', rating: 78 },
      { name: 'Hugo Sánchez',      position: 'ST', rating: 86 },
      { name: 'Carlos Hermosillo', position: 'LW', rating: 77 },
    ],
  },

  // ── UNGARN ───────────────────────────────────────────────────────────
  'ungarn:1966': {
    formation: '4-2-4', teamLabel: 'Hungría (1966)',
    source: 'Hungary - World Cup 1966',
    ratings: { attack: 80, midfield: 76, defense: 74, goalkeeping: 73 },
    players: [
      { name: 'József Gelei',      position: 'GK', rating: 74 },
      { name: 'Sándor Mátrai',     position: 'RB', rating: 74 },
      { name: 'Kálmán Mészöly',    position: 'CB', rating: 78 },
      { name: 'Mihály Dunai',      position: 'CB', rating: 74 },
      { name: 'Ferenc Sipos',      position: 'LB', rating: 73 },
      { name: 'László Puskás',     position: 'DM', rating: 75 },
      { name: 'Ferenc Bene',       position: 'CM', rating: 80 },
      { name: 'János Farkas',      position: 'RW', rating: 79 },
      { name: 'Flórián Albert',    position: 'AM', rating: 84 },
      { name: 'Dezső Novák',       position: 'ST', rating: 77 },
      { name: 'Imre Mathesz',      position: 'LW', rating: 76 },
    ],
  },
  'ungarn:1970': {
    formation: '4-3-3', teamLabel: 'Hungría (1970)',
    source: 'Hungary - World Cup 1970',
    ratings: { attack: 77, midfield: 75, defense: 73, goalkeeping: 72 },
    players: [
      { name: 'Antal Szentmihályi', position: 'GK', rating: 73 },
      { name: 'Sándor Mátrai',     position: 'RB', rating: 73 },
      { name: 'Lajos Dunai',       position: 'CB', rating: 74 },
      { name: 'Mihály Dunai',      position: 'CB', rating: 73 },
      { name: 'Lajos Kocsis',      position: 'LB', rating: 72 },
      { name: 'Lajos Szűcs',       position: 'DM', rating: 74 },
      { name: 'László Fazekas',    position: 'CM', rating: 76 },
      { name: 'István Szoke',      position: 'CM', rating: 75 },
      { name: 'Ferenc Bene',       position: 'RW', rating: 78 },
      { name: 'Ede Dunai',         position: 'ST', rating: 76 },
      { name: 'Zoltán Varga',      position: 'LW', rating: 77 },
    ],
  },
  'ungarn:1978': {
    formation: '4-4-2', teamLabel: 'Hungría (1978)',
    source: 'Hungary - World Cup 1978',
    ratings: { attack: 74, midfield: 73, defense: 72, goalkeeping: 71 },
    players: [
      { name: 'Sándor Gujdár',     position: 'GK', rating: 72 },
      { name: 'József Tóth',       position: 'RB', rating: 71 },
      { name: 'Tibor Rab',         position: 'CB', rating: 72 },
      { name: 'Miklós Páncsics',   position: 'CB', rating: 71 },
      { name: 'László Balint',     position: 'LB', rating: 71 },
      { name: 'Imre Garaba',       position: 'DM', rating: 72 },
      { name: 'Tibor Nyilasi',     position: 'CM', rating: 76 },
      { name: 'László Fazekas',    position: 'CM', rating: 75 },
      { name: 'András Töröcsik',   position: 'AM', rating: 77 },
      { name: 'Sándor Zombori',    position: 'ST', rating: 73 },
      { name: 'Karoly Csapo',      position: 'ST', rating: 72 },
    ],
  },
  'ungarn:1982': {
    formation: '4-4-2', teamLabel: 'Hungría (1982)',
    source: 'Hungary - World Cup 1982',
    ratings: { attack: 75, midfield: 74, defense: 72, goalkeeping: 71 },
    players: [
      { name: 'Ferenc Mészáros',   position: 'GK', rating: 72 },
      { name: 'Péter Várhidi',     position: 'RB', rating: 72 },
      { name: 'Tibor Rab',         position: 'CB', rating: 73 },
      { name: 'Imre Garaba',       position: 'CB', rating: 73 },
      { name: 'László Balint',     position: 'LB', rating: 71 },
      { name: 'Tibor Nyilasi',     position: 'CM', rating: 77 },
      { name: 'Laszlo Fazekas',    position: 'CM', rating: 74 },
      { name: 'Sándor Sallai',     position: 'DM', rating: 72 },
      { name: 'László Kiss',       position: 'AM', rating: 76 },
      { name: 'Géza Toldi',        position: 'ST', rating: 74 },
      { name: 'György Kerekes',    position: 'ST', rating: 73 },
    ],
  },

  // ── BULGARIEN ─────────────────────────────────────────────────────────
  'bulgarien:1966': {
    formation: '4-4-2', teamLabel: 'Bulgaria (1966)',
    source: 'Bulgaria - World Cup 1966',
    ratings: { attack: 76, midfield: 74, defense: 73, goalkeeping: 72 },
    players: [
      { name: 'Georgi Naidenov',   position: 'GK', rating: 73 },
      { name: 'Dimitar Largov',    position: 'RB', rating: 73 },
      { name: 'Boris Gaganelov',   position: 'CB', rating: 74 },
      { name: 'Aleksandar Shalamanov', position: 'CB', rating: 73 },
      { name: 'Ivan Davidov',      position: 'LB', rating: 72 },
      { name: 'Georgi Asparuhov',  position: 'CM', rating: 81 },
      { name: 'Ivan Kolev',        position: 'DM', rating: 75 },
      { name: 'Georgi Sokolov',    position: 'CM', rating: 74 },
      { name: 'Todor Diev',        position: 'AM', rating: 76 },
      { name: 'Ivan Dermendzhiev', position: 'ST', rating: 76 },
      { name: 'Dinko Dermendzhiev', position: 'LW', rating: 74 },
    ],
  },
  'bulgarien:1970': {
    formation: '4-4-2', teamLabel: 'Bulgaria (1970)',
    source: 'Bulgaria - World Cup 1970',
    ratings: { attack: 75, midfield: 73, defense: 72, goalkeeping: 71 },
    players: [
      { name: 'Simeon Simeonov',   position: 'GK', rating: 72 },
      { name: 'Aleksandar Shalamanov', position: 'RB', rating: 72 },
      { name: 'Boris Gaganelov',   position: 'CB', rating: 73 },
      { name: 'Georg Filipov',     position: 'CB', rating: 72 },
      { name: 'Rumen Goranov',     position: 'LB', rating: 71 },
      { name: 'Georgi Asparuhov',  position: 'CM', rating: 79 },
      { name: 'Ivan Kolev',        position: 'DM', rating: 73 },
      { name: 'Georgi Sokolov',    position: 'CM', rating: 73 },
      { name: 'Petar Zhekov',      position: 'ST', rating: 76 },
      { name: 'Milko Gaydarski',   position: 'ST', rating: 73 },
      { name: 'Hristo Bonev',      position: 'LW', rating: 76 },
    ],
  },
  'bulgarien:1974': {
    formation: '4-4-2', teamLabel: 'Bulgaria (1974)',
    source: 'Bulgaria - World Cup 1974',
    ratings: { attack: 75, midfield: 74, defense: 73, goalkeeping: 72 },
    players: [
      { name: 'Stoyan Yordanov',   position: 'GK', rating: 72 },
      { name: 'Kiril Ivkov',       position: 'RB', rating: 73 },
      { name: 'Nikola Arabov',     position: 'CB', rating: 74 },
      { name: 'Georg Filipov',     position: 'CB', rating: 73 },
      { name: 'Rumen Goranov',     position: 'LB', rating: 72 },
      { name: 'Hristo Bonev',      position: 'CM', rating: 78 },
      { name: 'Ivan Kolev',        position: 'DM', rating: 73 },
      { name: 'Petar Zhekov',      position: 'ST', rating: 76 },
      { name: 'Mikhail Minchev',   position: 'CM', rating: 73 },
      { name: 'Dinu Stankov',      position: 'ST', rating: 73 },
      { name: 'Dimitar Milenov',   position: 'LW', rating: 73 },
    ],
  },
  'bulgarien:1998': {
    formation: '4-4-2', teamLabel: 'Bulgaria (1998)',
    source: 'Bulgaria - World Cup 1998',
    ratings: { attack: 77, midfield: 76, defense: 75, goalkeeping: 74 },
    players: [
      { name: 'Zdravko Zdravkov',  position: 'GK', rating: 75 },
      { name: 'Trifon Ivanov',     position: 'CB', rating: 77 },
      { name: 'Zlatan Yankov',     position: 'CB', rating: 75 },
      { name: 'Emil Kremenliev',   position: 'RB', rating: 74 },
      { name: 'Petar Hubchev',     position: 'LB', rating: 75 },
      { name: 'Krasimir Balakov',  position: 'CM', rating: 80 },
      { name: 'Stilian Petrov',    position: 'CM', rating: 77 },
      { name: 'Daniel Borimirov',  position: 'DM', rating: 74 },
      { name: 'Hristo Stoichkov',  position: 'AM', rating: 83 },
      { name: 'Petar Aleksandrov', position: 'ST', rating: 75 },
      { name: 'Ilian Kiriakov',    position: 'LW', rating: 74 },
    ],
  },

  // ── RUMANIA ───────────────────────────────────────────────────────────
  'rumania:1970': {
    formation: '4-4-2', teamLabel: 'Rumania (1970)',
    source: 'Romania - World Cup 1970',
    ratings: { attack: 76, midfield: 74, defense: 73, goalkeeping: 72 },
    players: [
      { name: 'Stere Adamache',    position: 'GK', rating: 73 },
      { name: 'Mircea Sătmăreanu', position: 'RB', rating: 72 },
      { name: 'Mihai Mocanu',      position: 'CB', rating: 74 },
      { name: 'Nicolae Lupescu',   position: 'CB', rating: 73 },
      { name: 'Ion Dinu',          position: 'LB', rating: 72 },
      { name: 'Mihai Dobrescu',    position: 'DM', rating: 73 },
      { name: 'Radu Nunweiller',   position: 'CM', rating: 74 },
      { name: 'Cornel Dinu',       position: 'CM', rating: 76 },
      { name: 'Florentin Dumitrache', position: 'AM', rating: 78 },
      { name: 'Lucescu',           position: 'ST', rating: 77 },
      { name: 'Ion Ionescu',       position: 'LW', rating: 74 },
    ],
  },
  'rumania:1990': {
    formation: '4-4-2', teamLabel: 'Rumania (1990)',
    source: 'Romania - World Cup 1990',
    ratings: { attack: 80, midfield: 79, defense: 77, goalkeeping: 76 },
    players: [
      { name: 'Silviu Lung',       position: 'GK', rating: 77 },
      { name: 'Miodrag Belodedici', position: 'CB', rating: 79 },
      { name: 'Dan Petrescu',      position: 'RB', rating: 80 },
      { name: 'Ioan Andone',       position: 'CB', rating: 78 },
      { name: 'Gheorghe Popescu',  position: 'LB', rating: 81 },
      { name: 'Marius Lăcătuș',   position: 'RM', rating: 80 },
      { name: 'Rodion Cămătaru',   position: 'DM', rating: 76 },
      { name: 'Iosif Rotariu',     position: 'CM', rating: 77 },
      { name: 'Gheorghe Hagi',     position: 'AM', rating: 88 },
      { name: 'Florin Răducioiu',  position: 'ST', rating: 79 },
      { name: 'Ioan Sabau',        position: 'LW', rating: 76 },
    ],
  },

  // ── CHILE ─────────────────────────────────────────────────────────────
  'chile:1966': {
    formation: '4-4-2', teamLabel: 'Chile (1966)',
    source: 'Chile - World Cup 1966',
    ratings: { attack: 75, midfield: 73, defense: 73, goalkeeping: 72 },
    players: [
      { name: 'Misael Escuti',     position: 'GK', rating: 73 },
      { name: 'Héctor Rodríguez',  position: 'RB', rating: 72 },
      { name: 'Raúl Sánchez',      position: 'CB', rating: 74 },
      { name: 'Humberto Cruz',     position: 'CB', rating: 73 },
      { name: 'Alberto Valentini', position: 'LB', rating: 72 },
      { name: 'Guillermo Yávar',   position: 'DM', rating: 73 },
      { name: 'Alberto Fouilloux', position: 'CM', rating: 74 },
      { name: 'Pedro Araya',       position: 'CM', rating: 73 },
      { name: 'Leonel Sánchez',    position: 'AM', rating: 78 },
      { name: 'Rubén Marcos',      position: 'ST', rating: 74 },
      { name: 'Armando Tobar',     position: 'LW', rating: 73 },
    ],
  },
  'chile:1974': {
    formation: '4-4-2', teamLabel: 'Chile (1974)',
    source: 'Chile - World Cup 1974',
    ratings: { attack: 76, midfield: 74, defense: 73, goalkeeping: 72 },
    players: [
      { name: 'Leopoldo Vallejos', position: 'GK', rating: 73 },
      { name: 'Eduardo Herrera',   position: 'RB', rating: 73 },
      { name: 'Elías Figueroa',    position: 'CB', rating: 83 },
      { name: 'Mario Galindo',     position: 'CB', rating: 74 },
      { name: 'Manuel Valencia',   position: 'LB', rating: 72 },
      { name: 'Carlos Reinoso',    position: 'DM', rating: 75 },
      { name: 'Bernardo Valdés',   position: 'CM', rating: 74 },
      { name: 'Carlos Caszely',    position: 'AM', rating: 80 },
      { name: 'Leonel Herrera',    position: 'CM', rating: 73 },
      { name: 'Juan Morales',      position: 'ST', rating: 74 },
      { name: 'Victor Segundo',    position: 'LW', rating: 73 },
    ],
  },
  'chile:1982': {
    formation: '4-4-2', teamLabel: 'Chile (1982)',
    source: 'Chile - World Cup 1982',
    ratings: { attack: 74, midfield: 73, defense: 72, goalkeeping: 71 },
    players: [
      { name: 'Mario Osbén',       position: 'GK', rating: 72 },
      { name: 'Patricio Yáñez',    position: 'RB', rating: 72 },
      { name: 'Elías Figueroa',    position: 'CB', rating: 80 },
      { name: 'Carlos Toro',       position: 'CB', rating: 72 },
      { name: 'Alejandro Hisis',   position: 'LB', rating: 71 },
      { name: 'Juan Letelier',     position: 'DM', rating: 72 },
      { name: 'René Valenzuela',   position: 'CM', rating: 73 },
      { name: 'Iván Zamorano Sr.', position: 'CM', rating: 72 },
      { name: 'Carlos Caszely',    position: 'AM', rating: 77 },
      { name: 'Luis Santibáñez',   position: 'ST', rating: 73 },
      { name: 'Fernando Astengo',  position: 'LW', rating: 72 },
    ],
  },

  // ── PERÚ ─────────────────────────────────────────────────────────────
  'peru:1970': {
    formation: '4-4-2', teamLabel: 'Perú (1970)',
    source: 'Peru - World Cup 1970 (QF)',
    ratings: { attack: 78, midfield: 76, defense: 74, goalkeeping: 73 },
    players: [
      { name: 'Luis Rubiños',      position: 'GK', rating: 74 },
      { name: 'Pedro Gonzales',    position: 'RB', rating: 73 },
      { name: 'Héctor Chumpitaz',  position: 'CB', rating: 79 },
      { name: 'Roberto Challe',    position: 'CB', rating: 74 },
      { name: 'Néstor Drago',      position: 'LB', rating: 73 },
      { name: 'Percy Rojas',       position: 'DM', rating: 76 },
      { name: 'Ramón Mifflin',     position: 'CM', rating: 77 },
      { name: 'Oswaldo Ramírez',   position: 'CM', rating: 75 },
      { name: 'Hugo Sotil',        position: 'RW', rating: 78 },
      { name: 'Teófilo Cubillas',  position: 'AM', rating: 84 },
      { name: 'Pedro León',        position: 'ST', rating: 76 },
    ],
  },
  'peru:1978': {
    formation: '4-3-3', teamLabel: 'Perú (1978)',
    source: 'Peru - World Cup 1978 (QF)',
    ratings: { attack: 80, midfield: 78, defense: 76, goalkeeping: 75 },
    players: [
      { name: 'Ramón Quiroga',     position: 'GK', rating: 76 },
      { name: 'Jorge Muñante',     position: 'RB', rating: 75 },
      { name: 'Héctor Chumpitaz',  position: 'CB', rating: 80 },
      { name: 'Roberto Rojas',     position: 'CB', rating: 75 },
      { name: 'Jaime Duarte',      position: 'LB', rating: 74 },
      { name: 'José Velásquez',    position: 'DM', rating: 77 },
      { name: 'Julio Meléndez',    position: 'CM', rating: 76 },
      { name: 'Ramón Mifflin',     position: 'CM', rating: 76 },
      { name: 'Hugo Sotil',        position: 'RW', rating: 79 },
      { name: 'Teófilo Cubillas',  position: 'AM', rating: 85 },
      { name: 'César Cueto',       position: 'LW', rating: 78 },
    ],
  },
  'peru:1982': {
    formation: '4-4-2', teamLabel: 'Perú (1982)',
    source: 'Peru - World Cup 1982',
    ratings: { attack: 74, midfield: 73, defense: 72, goalkeeping: 71 },
    players: [
      { name: 'Ramón Quiroga',     position: 'GK', rating: 72 },
      { name: 'Jorge Olaechea',    position: 'RB', rating: 72 },
      { name: 'Didí Sánchez',      position: 'CB', rating: 72 },
      { name: 'Jorge Muñante',     position: 'CB', rating: 72 },
      { name: 'Reyes Ramos',       position: 'LB', rating: 71 },
      { name: 'César Cueto',       position: 'CM', rating: 77 },
      { name: 'José Velásquez',    position: 'DM', rating: 74 },
      { name: 'Teófilo Cubillas',  position: 'AM', rating: 80 },
      { name: 'Uribe Marcos',      position: 'CM', rating: 72 },
      { name: 'Roberto Guerrero',  position: 'ST', rating: 72 },
      { name: 'Luis Reyes',        position: 'LW', rating: 72 },
    ],
  },

  // ── MAROKKO ───────────────────────────────────────────────────────────
  'marokko:1970': {
    formation: '4-4-2', teamLabel: 'Marruecos (1970)',
    source: 'Morocco - World Cup 1970',
    ratings: { attack: 71, midfield: 70, defense: 70, goalkeeping: 69 },
    players: [
      { name: 'Allal Ben Kassou',  position: 'GK', rating: 70 },
      { name: 'Mohamed Maaroufi',  position: 'RB', rating: 70 },
      { name: 'Boujemaa Benkhrif', position: 'CB', rating: 71 },
      { name: 'Mohamed Meknassi',  position: 'CB', rating: 70 },
      { name: 'Brahim Taj',        position: 'LB', rating: 70 },
      { name: 'Ahmed Faras',       position: 'CM', rating: 73 },
      { name: 'Khalil Azmi',       position: 'DM', rating: 70 },
      { name: 'Abderrazak Khairi', position: 'CM', rating: 71 },
      { name: 'Mbarek Touibi',     position: 'RW', rating: 71 },
      { name: 'Houmane Jarir',     position: 'ST', rating: 71 },
      { name: 'Mohamed Ghazouani', position: 'LW', rating: 70 },
    ],
  },
  'marokko:1986': {
    formation: '4-4-2', teamLabel: 'Marruecos (1986)',
    source: 'Morocco - World Cup 1986 (R16, group leaders)',
    ratings: { attack: 76, midfield: 74, defense: 74, goalkeeping: 73 },
    players: [
      { name: 'Badou Zaki',        position: 'GK', rating: 74 },
      { name: 'Lahcen Abrami',     position: 'RB', rating: 73 },
      { name: 'Aziz Bouderbala',   position: 'CB', rating: 75 },
      { name: 'Mohamed Bouyahiaoui', position: 'CB', rating: 74 },
      { name: 'El Haddaoui',       position: 'LB', rating: 73 },
      { name: 'Mustafa El Haddaoui', position: 'DM', rating: 74 },
      { name: 'Moustapha Merry',   position: 'CM', rating: 75 },
      { name: 'Abdelmajid Dolmy',  position: 'CM', rating: 77 },
      { name: 'Baddou Zaki',       position: 'AM', rating: 74 },
      { name: 'Ahmed Faras',       position: 'ST', rating: 76 },
      { name: 'Abderrazak Khairi', position: 'LW', rating: 74 },
    ],
  },
  'marokko:1994': {
    formation: '4-4-2', teamLabel: 'Marruecos (1994)',
    source: 'Morocco - World Cup 1994',
    ratings: { attack: 74, midfield: 73, defense: 73, goalkeeping: 72 },
    players: [
      { name: 'Khalil Azmi',       position: 'GK', rating: 72 },
      { name: 'Abdeslam Laghrissi', position: 'RB', rating: 72 },
      { name: 'Noureddine Naybet', position: 'CB', rating: 77 },
      { name: 'Rachid Daoudi',     position: 'CB', rating: 73 },
      { name: 'Mustapha El Haddaoui', position: 'LB', rating: 72 },
      { name: 'Rachid Azzouzi',    position: 'DM', rating: 73 },
      { name: 'Mustapha Hadji',    position: 'CM', rating: 78 },
      { name: 'Abdelkrim El Hadrioui', position: 'CM', rating: 73 },
      { name: 'Tahar El Khalej',   position: 'AM', rating: 74 },
      { name: 'Said Chiba',        position: 'ST', rating: 73 },
      { name: 'Younès Kaboul',     position: 'LW', rating: 72 },
    ],
  },
  'marokko:1998': {
    formation: '4-4-2', teamLabel: 'Marruecos (1998)',
    source: 'Morocco - World Cup 1998',
    ratings: { attack: 75, midfield: 74, defense: 73, goalkeeping: 72 },
    players: [
      { name: 'Driss Benzekri',    position: 'GK', rating: 73 },
      { name: 'Abdelkhalek Losri', position: 'RB', rating: 73 },
      { name: 'Noureddine Naybet', position: 'CB', rating: 78 },
      { name: 'Rachid El Hadrioui', position: 'CB', rating: 73 },
      { name: 'Abdelouahed Naybet', position: 'LB', rating: 72 },
      { name: 'Rachid Azzouzi',    position: 'DM', rating: 73 },
      { name: 'Mustapha Hadji',    position: 'CM', rating: 79 },
      { name: 'Hicham Zerouali',   position: 'CM', rating: 76 },
      { name: 'Salaheddine Bassir', position: 'AM', rating: 75 },
      { name: 'Abdeljalil Hadda',  position: 'ST', rating: 73 },
      { name: 'Youssef Chippo',    position: 'LW', rating: 75 },
    ],
  },

  // ── KONGO (Zaire/RD Congo) ────────────────────────────────────────────
  'kongo:1974': {
    formation: '4-4-2', teamLabel: 'Zaire (1974)',
    source: 'Zaire/DR Congo - World Cup 1974',
    ratings: { attack: 67, midfield: 66, defense: 66, goalkeeping: 65 },
    players: [
      { name: 'Kazadi Mwamba',     position: 'GK', rating: 66 },
      { name: 'Mwepu Ilunga',      position: 'RB', rating: 67 },
      { name: 'Bwanga Tshimen',    position: 'CB', rating: 67 },
      { name: 'Lobilo Boba',       position: 'CB', rating: 66 },
      { name: 'Mana Mamuwene',     position: 'LB', rating: 66 },
      { name: 'Kembo Uba',         position: 'DM', rating: 66 },
      { name: 'Kilasu Massamba',   position: 'CM', rating: 68 },
      { name: 'Mulamba Ndaye',     position: 'CM', rating: 70 },
      { name: 'Ntumba Kabila',     position: 'RW', rating: 67 },
      { name: 'Kidumu Mantantu',   position: 'ST', rating: 67 },
      { name: 'Mayanga Maku',      position: 'LW', rating: 67 },
    ],
  },

  // ── ALGERIEN ─────────────────────────────────────────────────────────
  'algerien:1982': {
    formation: '4-3-3', teamLabel: 'Argelia (1982)',
    source: 'Algeria - World Cup 1982 (beat W.Germany)',
    ratings: { attack: 77, midfield: 75, defense: 74, goalkeeping: 73 },
    players: [
      { name: 'Cerbah',            position: 'GK', rating: 73 },
      { name: 'Mansouri',          position: 'RB', rating: 74 },
      { name: 'Guendouz',          position: 'CB', rating: 75 },
      { name: 'Merzekane',         position: 'CB', rating: 75 },
      { name: 'Kourichi',          position: 'LB', rating: 73 },
      { name: 'Belloumi',          position: 'CM', rating: 82 },
      { name: 'Madjer',            position: 'CM', rating: 81 },
      { name: 'Dahleb',            position: 'DM', rating: 75 },
      { name: 'Assad',             position: 'RW', rating: 77 },
      { name: 'Bensaoula',         position: 'ST', rating: 76 },
      { name: 'Fergani',           position: 'LW', rating: 74 },
    ],
  },
  'algerien:1986': {
    formation: '4-4-2', teamLabel: 'Argelia (1986)',
    source: 'Algeria - World Cup 1986',
    ratings: { attack: 74, midfield: 73, defense: 72, goalkeeping: 71 },
    players: [
      { name: 'Drid',              position: 'GK', rating: 72 },
      { name: 'Mansouri',          position: 'RB', rating: 72 },
      { name: 'Guendouz',          position: 'CB', rating: 73 },
      { name: 'Kourichi',          position: 'CB', rating: 72 },
      { name: 'Larbi',             position: 'LB', rating: 71 },
      { name: 'Madjer',            position: 'CM', rating: 79 },
      { name: 'Belloumi',          position: 'CM', rating: 80 },
      { name: 'Megharia',          position: 'DM', rating: 72 },
      { name: 'Assad',             position: 'RW', rating: 75 },
      { name: 'Bensaoula',         position: 'ST', rating: 74 },
      { name: 'Oudjani',           position: 'LW', rating: 72 },
    ],
  },
  'algerien:2010': {
    formation: '4-4-2', teamLabel: 'Argelia (2010)',
    source: 'Algeria - World Cup 2010',
    ratings: { attack: 72, midfield: 72, defense: 73, goalkeeping: 72 },
    players: [
      { name: 'Faouzi Chaouchi',   position: 'GK', rating: 73 },
      { name: 'Madjid Bougherra',  position: 'CB', rating: 78 },
      { name: 'Antar Yahia',       position: 'CB', rating: 74 },
      { name: 'Rafik Halliche',    position: 'RB', rating: 73 },
      { name: 'Nadir Belhadj',     position: 'LB', rating: 74 },
      { name: 'Karim Ziani',       position: 'CM', rating: 76 },
      { name: 'Yazid Mansouri',    position: 'DM', rating: 73 },
      { name: 'Hassan Yebda',      position: 'CM', rating: 74 },
      { name: 'Abdelkader Ghezzal', position: 'RW', rating: 72 },
      { name: 'Rafik Djebbour',    position: 'ST', rating: 73 },
      { name: 'Foued Kadir',       position: 'LW', rating: 73 },
    ],
  },
  'algerien:2014': {
    formation: '4-3-3', teamLabel: 'Argelia (2014)',
    source: 'Algeria - World Cup 2014 (R16)',
    ratings: { attack: 76, midfield: 75, defense: 74, goalkeeping: 73 },
    players: [
      { name: 'Raïs M\'Bolhi',     position: 'GK', rating: 74 },
      { name: 'Madjid Bougherra',  position: 'CB', rating: 77 },
      { name: 'Essaïd Belkalem',   position: 'CB', rating: 74 },
      { name: 'Rafik Halliche',    position: 'RB', rating: 73 },
      { name: 'Faouzi Ghoulam',    position: 'LB', rating: 78 },
      { name: 'Medhi Lacen',       position: 'DM', rating: 75 },
      { name: 'Sofiane Feghouli',  position: 'CM', rating: 79 },
      { name: 'Nabil Bentaleb',    position: 'CM', rating: 76 },
      { name: 'Yacine Brahimi',    position: 'RW', rating: 79 },
      { name: 'Islam Slimani',     position: 'ST', rating: 79 },
      { name: 'Abdelmoumène Djabou', position: 'LW', rating: 73 },
    ],
  },

  // ── KAMERUN ───────────────────────────────────────────────────────────
  'kamerun:1982': {
    formation: '4-4-2', teamLabel: 'Camerún (1982)',
    source: 'Cameroon - World Cup 1982',
    ratings: { attack: 74, midfield: 72, defense: 73, goalkeeping: 71 },
    players: [
      { name: 'Thomas N\'Kono',    position: 'GK', rating: 76 },
      { name: 'Emmanuel Kunde',    position: 'CB', rating: 73 },
      { name: 'Théophile Abega',   position: 'CM', rating: 76 },
      { name: 'Jean Manga Onguéné', position: 'RB', rating: 72 },
      { name: 'Victor Ndip',       position: 'CB', rating: 72 },
      { name: 'Michel Kaham',      position: 'LB', rating: 71 },
      { name: 'Grégoire Mbida',    position: 'DM', rating: 72 },
      { name: 'Roger Milla',       position: 'AM', rating: 79 },
      { name: 'Eugène Ekéké',      position: 'RW', rating: 73 },
      { name: 'Pius Ndiefi',       position: 'ST', rating: 72 },
      { name: 'René Ndjeya',       position: 'LW', rating: 71 },
    ],
  },
  'kamerun:1994': {
    formation: '4-4-2', teamLabel: 'Camerún (1994)',
    source: 'Cameroon - World Cup 1994',
    ratings: { attack: 75, midfield: 73, defense: 73, goalkeeping: 74 },
    players: [
      { name: 'Jacques Songo\'o',  position: 'GK', rating: 75 },
      { name: 'Stephen Tataw',     position: 'CB', rating: 73 },
      { name: 'Rigobert Song',     position: 'CB', rating: 77 },
      { name: 'Michel Kaham',      position: 'RB', rating: 72 },
      { name: 'Raymond Kalla',     position: 'LB', rating: 72 },
      { name: 'François Omam-Biyik', position: 'CM', rating: 76 },
      { name: 'Marc-Vivien Foé',   position: 'DM', rating: 78 },
      { name: 'Joseph-Antoine Bell', position: 'CM', rating: 72 },
      { name: 'David Embé',        position: 'RW', rating: 73 },
      { name: 'Patrick Mboma',     position: 'ST', rating: 80 },
      { name: 'Emile Mbouh',       position: 'LW', rating: 72 },
    ],
  },
  'kamerun:1998': {
    formation: '4-4-2', teamLabel: 'Camerún (1998)',
    source: 'Cameroon - World Cup 1998',
    ratings: { attack: 75, midfield: 74, defense: 73, goalkeeping: 74 },
    players: [
      { name: 'Jacques Songo\'o',  position: 'GK', rating: 75 },
      { name: 'Rigobert Song',     position: 'CB', rating: 79 },
      { name: 'Cyrille Njitap',    position: 'CB', rating: 73 },
      { name: 'Pierre Wome',       position: 'LB', rating: 75 },
      { name: 'Hans Agbo',         position: 'RB', rating: 72 },
      { name: 'Marc-Vivien Foé',   position: 'DM', rating: 79 },
      { name: 'Geremi',            position: 'CM', rating: 78 },
      { name: 'Raymond Kalla',     position: 'CM', rating: 73 },
      { name: 'Samuel Eto\'o',     position: 'RW', rating: 75 },
      { name: 'Patrick Mboma',     position: 'ST', rating: 81 },
      { name: 'Alphonse Tchami',   position: 'LW', rating: 73 },
    ],
  },
  'kamerun:2002': {
    formation: '4-3-3', teamLabel: 'Camerún (2002)',
    source: 'Cameroon - World Cup 2002',
    ratings: { attack: 76, midfield: 75, defense: 74, goalkeeping: 74 },
    players: [
      { name: 'Boukar Alioum',     position: 'GK', rating: 74 },
      { name: 'Rigobert Song',     position: 'CB', rating: 78 },
      { name: 'Geremi',            position: 'RB', rating: 79 },
      { name: 'Pierre Wome',       position: 'LB', rating: 76 },
      { name: 'Timothée Atouba',   position: 'CB', rating: 74 },
      { name: 'Marc-Vivien Foé',   position: 'DM', rating: 80 },
      { name: 'Lauren',            position: 'CM', rating: 77 },
      { name: 'Bill Tchato',       position: 'CM', rating: 73 },
      { name: 'Samuel Eto\'o',     position: 'ST', rating: 82 },
      { name: 'Patrick Mboma',     position: 'ST', rating: 79 },
      { name: 'Salomon Olembe',    position: 'LW', rating: 73 },
    ],
  },
  'kamerun:2010': {
    formation: '4-3-3', teamLabel: 'Camerún (2010)',
    source: 'Cameroon - World Cup 2010',
    ratings: { attack: 74, midfield: 73, defense: 72, goalkeeping: 72 },
    players: [
      { name: 'Carlos Kameni',     position: 'GK', rating: 73 },
      { name: 'Rigobert Song',     position: 'CB', rating: 74 },
      { name: 'Nicolas Nkoulou',   position: 'CB', rating: 75 },
      { name: 'Aurelien Chedjou',  position: 'LB', rating: 74 },
      { name: 'Benoit Assou-Ekotto', position: 'RB', rating: 74 },
      { name: 'Stephane Mbia',     position: 'DM', rating: 76 },
      { name: 'Alex Song',         position: 'CM', rating: 77 },
      { name: 'Jean Makoun',       position: 'CM', rating: 74 },
      { name: 'Samuel Eto\'o',     position: 'ST', rating: 85 },
      { name: 'Mohamadou Idrissou', position: 'ST', rating: 72 },
      { name: 'Achille Emana',     position: 'LW', rating: 73 },
    ],
  },

  // ── NIGERIA ───────────────────────────────────────────────────────────
  'nigeria:1994': {
    formation: '4-4-2', teamLabel: 'Nigeria (1994)',
    source: 'Nigeria - World Cup 1994 (R16)',
    ratings: { attack: 79, midfield: 77, defense: 75, goalkeeping: 74 },
    players: [
      { name: 'Peter Rufai',       position: 'GK', rating: 75 },
      { name: 'Uche Okechukwu',    position: 'CB', rating: 76 },
      { name: 'Ben Iroha',         position: 'CB', rating: 74 },
      { name: 'Chidi Nwanu',       position: 'RB', rating: 74 },
      { name: 'Finidi George',     position: 'LB', rating: 79 },
      { name: 'Jay-Jay Okocha',    position: 'CM', rating: 83 },
      { name: 'Emmanuel Amuneke',  position: 'CM', rating: 79 },
      { name: 'Sunday Oliseh',     position: 'DM', rating: 77 },
      { name: 'Rashidi Yekini',    position: 'ST', rating: 81 },
      { name: 'Daniel Amokachi',   position: 'ST', rating: 78 },
      { name: 'Nwankwo Kanu',      position: 'AM', rating: 75 },
    ],
  },
  'nigeria:1998': {
    formation: '4-4-2', teamLabel: 'Nigeria (1998)',
    source: 'Nigeria - World Cup 1998',
    ratings: { attack: 78, midfield: 76, defense: 74, goalkeeping: 73 },
    players: [
      { name: 'Peter Rufai',       position: 'GK', rating: 74 },
      { name: 'Taribo West',       position: 'CB', rating: 78 },
      { name: 'Uche Okechukwu',    position: 'CB', rating: 75 },
      { name: 'Celestine Babayaro', position: 'LB', rating: 77 },
      { name: 'Finidi George',     position: 'RB', rating: 78 },
      { name: 'Jay-Jay Okocha',    position: 'CM', rating: 84 },
      { name: 'Sunday Oliseh',     position: 'DM', rating: 77 },
      { name: 'Emmanuel Amuneke',  position: 'CM', rating: 77 },
      { name: 'Nwankwo Kanu',      position: 'AM', rating: 82 },
      { name: 'Rashidi Yekini',    position: 'ST', rating: 78 },
      { name: 'Victor Ikpeba',     position: 'LW', rating: 76 },
    ],
  },
  'nigeria:2002': {
    formation: '4-3-3', teamLabel: 'Nigeria (2002)',
    source: 'Nigeria - World Cup 2002',
    ratings: { attack: 74, midfield: 73, defense: 72, goalkeeping: 71 },
    players: [
      { name: 'Ike Shorunmu',      position: 'GK', rating: 72 },
      { name: 'Taribo West',       position: 'CB', rating: 75 },
      { name: 'Joseph Yobo',       position: 'CB', rating: 75 },
      { name: 'Celestine Babayaro', position: 'LB', rating: 74 },
      { name: 'Ifeanyi Udeze',     position: 'RB', rating: 72 },
      { name: 'Jay-Jay Okocha',    position: 'CM', rating: 82 },
      { name: 'Nwankwo Kanu',      position: 'AM', rating: 79 },
      { name: 'Sunday Oliseh',     position: 'DM', rating: 74 },
      { name: 'Julius Aghahowa',   position: 'RW', rating: 74 },
      { name: 'Yakubu Aiyegbeni',  position: 'ST', rating: 77 },
      { name: 'Finidi George',     position: 'LW', rating: 75 },
    ],
  },
  'nigeria:2010': {
    formation: '4-4-2', teamLabel: 'Nigeria (2010)',
    source: 'Nigeria - World Cup 2010',
    ratings: { attack: 73, midfield: 72, defense: 72, goalkeeping: 71 },
    players: [
      { name: 'Vincent Enyeama',   position: 'GK', rating: 76 },
      { name: 'Joseph Yobo',       position: 'CB', rating: 76 },
      { name: 'Taye Taiwo',        position: 'LB', rating: 74 },
      { name: 'Chidi Odiah',       position: 'RB', rating: 72 },
      { name: 'Danny Shittu',      position: 'CB', rating: 73 },
      { name: 'John Obi Mikel',    position: 'DM', rating: 77 },
      { name: 'Sani Kaita',        position: 'CM', rating: 71 },
      { name: 'Yakubu Aiyegbeni',  position: 'ST', rating: 77 },
      { name: 'Peter Odemwingie',  position: 'RW', rating: 75 },
      { name: 'Obafemi Martins',   position: 'ST', rating: 74 },
      { name: 'Sani Oduya',        position: 'LW', rating: 71 },
    ],
  },
  'nigeria:2014': {
    formation: '4-3-3', teamLabel: 'Nigeria (2014)',
    source: 'Nigeria - World Cup 2014 (R16)',
    ratings: { attack: 76, midfield: 74, defense: 73, goalkeeping: 75 },
    players: [
      { name: 'Vincent Enyeama',   position: 'GK', rating: 78 },
      { name: 'Joseph Yobo',       position: 'CB', rating: 74 },
      { name: 'Efe Ambrose',       position: 'CB', rating: 72 },
      { name: 'Juwon Oshaniwa',    position: 'LB', rating: 71 },
      { name: 'Elderson Echiejile', position: 'RB', rating: 72 },
      { name: 'John Obi Mikel',    position: 'DM', rating: 77 },
      { name: 'Ogenyi Onazi',      position: 'CM', rating: 74 },
      { name: 'Victor Moses',      position: 'RW', rating: 76 },
      { name: 'Ahmed Musa',        position: 'LW', rating: 78 },
      { name: 'Peter Odemwingie',  position: 'AM', rating: 74 },
      { name: 'Emmanuel Emenike',  position: 'ST', rating: 75 },
    ],
  },
  'nigeria:2018': {
    formation: '4-2-3-1', teamLabel: 'Nigeria (2018)',
    source: 'Nigeria - World Cup 2018',
    ratings: { attack: 75, midfield: 73, defense: 72, goalkeeping: 74 },
    players: [
      { name: 'Francis Uzoho',     position: 'GK', rating: 73 },
      { name: 'William Troost-Ekong', position: 'CB', rating: 74 },
      { name: 'Leon Balogun',      position: 'CB', rating: 73 },
      { name: 'Tyronne Ebuehi',    position: 'RB', rating: 72 },
      { name: 'Brian Idowu',       position: 'LB', rating: 72 },
      { name: 'John Obi Mikel',    position: 'DM', rating: 75 },
      { name: 'Wilfred Ndidi',     position: 'DM', rating: 79 },
      { name: 'Ahmed Musa',        position: 'RW', rating: 78 },
      { name: 'Alex Iwobi',        position: 'AM', rating: 76 },
      { name: 'Victor Moses',      position: 'LW', rating: 75 },
      { name: 'Odion Ighalo',      position: 'ST', rating: 76 },
    ],
  },

  // ── IRAN ─────────────────────────────────────────────────────────────
  'iran:1978': {
    formation: '4-4-2', teamLabel: 'Irán (1978)',
    source: 'Iran - World Cup 1978',
    ratings: { attack: 73, midfield: 71, defense: 70, goalkeeping: 70 },
    players: [
      { name: 'Nasser Hejazi',     position: 'GK', rating: 71 },
      { name: 'Hassan Nazari',     position: 'RB', rating: 70 },
      { name: 'Andranik Eskandarian', position: 'CB', rating: 71 },
      { name: 'Hossein Kazerani',  position: 'CB', rating: 70 },
      { name: 'Jahangir Nazari',   position: 'LB', rating: 70 },
      { name: 'Iraj Danaeifar',    position: 'DM', rating: 71 },
      { name: 'Mehdi Rashidi',     position: 'CM', rating: 72 },
      { name: 'Parviz Ghlichkhani', position: 'CM', rating: 71 },
      { name: 'Ali Parvin',        position: 'AM', rating: 74 },
      { name: 'Hassan Rowshan',    position: 'ST', rating: 72 },
      { name: 'Nasser Nourayi',    position: 'LW', rating: 71 },
    ],
  },
  'iran:1998': {
    formation: '4-4-2', teamLabel: 'Irán (1998)',
    source: 'Iran - World Cup 1998',
    ratings: { attack: 73, midfield: 71, defense: 71, goalkeeping: 70 },
    players: [
      { name: 'Ahmad Abedzadeh',   position: 'GK', rating: 71 },
      { name: 'Mehdi Pashazadeh',  position: 'RB', rating: 70 },
      { name: 'Mohammad Khakpour', position: 'CB', rating: 71 },
      { name: 'Sirous Pourmousavi', position: 'CB', rating: 71 },
      { name: 'Jahanbakhsh Bakhshandeh', position: 'LB', rating: 70 },
      { name: 'Khodadad Azizi',    position: 'CM', rating: 75 },
      { name: 'Ali Daei',          position: 'ST', rating: 79 },
      { name: 'Mehdi Mahdavikia',  position: 'RW', rating: 74 },
      { name: 'Hamid Estili',      position: 'AM', rating: 73 },
      { name: 'Karim Bagheri',     position: 'CM', rating: 75 },
      { name: 'Reza Ghotbi',       position: 'LW', rating: 70 },
    ],
  },
  'iran:2006': {
    formation: '4-4-2', teamLabel: 'Irán (2006)',
    source: 'Iran - World Cup 2006',
    ratings: { attack: 71, midfield: 70, defense: 71, goalkeeping: 70 },
    players: [
      { name: 'Ebrahim Mirzapour', position: 'GK', rating: 71 },
      { name: 'Mohammad Nosrati',  position: 'LB', rating: 70 },
      { name: 'Hossein Kaebi',     position: 'CB', rating: 72 },
      { name: 'Yahya Golmohammadi', position: 'CB', rating: 71 },
      { name: 'Sohrab Bakhtiarizadeh', position: 'RB', rating: 70 },
      { name: 'Mehdi Mahdavikia',  position: 'RW', rating: 74 },
      { name: 'Jawad Nekounam',    position: 'DM', rating: 73 },
      { name: 'Andranik Teymourian', position: 'CM', rating: 72 },
      { name: 'Ali Karimi',        position: 'AM', rating: 76 },
      { name: 'Ali Daei',          position: 'ST', rating: 74 },
      { name: 'Vahid Hashemian',   position: 'LW', rating: 70 },
    ],
  },
  'iran:2014': {
    formation: '4-5-1', teamLabel: 'Irán (2014)',
    source: 'Iran - World Cup 2014',
    ratings: { attack: 70, midfield: 70, defense: 73, goalkeeping: 71 },
    players: [
      { name: 'Alireza Haghighi',  position: 'GK', rating: 72 },
      { name: 'Amir Sadeghi',      position: 'RB', rating: 71 },
      { name: 'Jalal Hosseini',    position: 'CB', rating: 73 },
      { name: 'Pejman Montazeri',  position: 'CB', rating: 72 },
      { name: 'Mohammad Reza Khalatbari', position: 'LB', rating: 71 },
      { name: 'Javad Nekounam',    position: 'DM', rating: 73 },
      { name: 'Andranik Teymourian', position: 'CM', rating: 71 },
      { name: 'Steven Beitashour', position: 'CM', rating: 71 },
      { name: 'Masoud Shojaei',    position: 'AM', rating: 73 },
      { name: 'Reza Ghoochannejhad', position: 'ST', rating: 73 },
      { name: 'Ashkan Dejagah',    position: 'LW', rating: 74 },
    ],
  },
  'iran:2018': {
    formation: '4-3-3', teamLabel: 'Irán (2018)',
    source: 'Iran - World Cup 2018',
    ratings: { attack: 72, midfield: 71, defense: 73, goalkeeping: 71 },
    players: [
      { name: 'Ali Beiranvand',    position: 'GK', rating: 74 },
      { name: 'Rouzbeh Cheshmi',   position: 'RB', rating: 71 },
      { name: 'Morteza Pouraliganji', position: 'CB', rating: 73 },
      { name: 'Milad Mohammadi',   position: 'LB', rating: 72 },
      { name: 'Pejman Montazeri',  position: 'CB', rating: 72 },
      { name: 'Saeid Ezatolahi',   position: 'DM', rating: 72 },
      { name: 'Masoud Shojaei',    position: 'CM', rating: 73 },
      { name: 'Omid Ebrahimi',     position: 'CM', rating: 72 },
      { name: 'Alireza Jahanbakhsh', position: 'RW', rating: 77 },
      { name: 'Sardar Azmoun',     position: 'ST', rating: 80 },
      { name: 'Reza Ghoochannejhad', position: 'LW', rating: 72 },
    ],
  },
  'iran:2022': {
    formation: '4-3-3', teamLabel: 'Irán (2022)',
    source: 'Iran - World Cup 2022',
    ratings: { attack: 73, midfield: 72, defense: 74, goalkeeping: 72 },
    players: [
      { name: 'Alireza Beiranvand', position: 'GK', rating: 73 },
      { name: 'Sadegh Moharrami',  position: 'RB', rating: 72 },
      { name: 'Morteza Pouraliganji', position: 'CB', rating: 74 },
      { name: 'Shojae Khalilzadeh', position: 'CB', rating: 73 },
      { name: 'Milad Mohammadi',   position: 'LB', rating: 73 },
      { name: 'Ahmad Noorollahi',  position: 'DM', rating: 72 },
      { name: 'Saeid Ezatolahi',   position: 'CM', rating: 74 },
      { name: 'Ali Gholizadeh',    position: 'CM', rating: 73 },
      { name: 'Alireza Jahanbakhsh', position: 'RW', rating: 78 },
      { name: 'Mehdi Taremi',      position: 'ST', rating: 82 },
      { name: 'Sardar Azmoun',     position: 'LW', rating: 79 },
    ],
  },

  // ── TUNESIEN ─────────────────────────────────────────────────────────
  'tunesien:1978': {
    formation: '4-4-2', teamLabel: 'Túnez (1978)',
    source: 'Tunisia - World Cup 1978 (first African win at WC)',
    ratings: { attack: 73, midfield: 72, defense: 71, goalkeeping: 70 },
    players: [
      { name: 'Ali Dhahri',        position: 'GK', rating: 71 },
      { name: 'Néjib Ghommidh',    position: 'RB', rating: 71 },
      { name: 'Amor Jelali',       position: 'CB', rating: 72 },
      { name: 'Lassaad Khalifa',   position: 'CB', rating: 71 },
      { name: 'Hedi M\'Nari',      position: 'LB', rating: 70 },
      { name: 'Tarak Dhiab',       position: 'CM', rating: 76 },
      { name: 'Aïssa Ayari',       position: 'DM', rating: 71 },
      { name: 'Mondher Chetali',   position: 'CM', rating: 72 },
      { name: 'Mokhtar Dhouieb',   position: 'RW', rating: 72 },
      { name: 'Néjib Ghommidh Jr.', position: 'ST', rating: 73 },
      { name: 'Khemais Labidi',    position: 'LW', rating: 72 },
    ],
  },
  'tunesien:1998': {
    formation: '4-4-2', teamLabel: 'Túnez (1998)',
    source: 'Tunisia - World Cup 1998',
    ratings: { attack: 72, midfield: 71, defense: 71, goalkeeping: 70 },
    players: [
      { name: 'Chokri El Ouaer',   position: 'GK', rating: 71 },
      { name: 'Mhamed Trabelsi',   position: 'RB', rating: 71 },
      { name: 'Karim Bagheri',     position: 'CB', rating: 71 },
      { name: 'Khaled Badra',      position: 'CB', rating: 71 },
      { name: 'Siaka Tiéné',       position: 'LB', rating: 70 },
      { name: 'Adel Sellimi',      position: 'CM', rating: 74 },
      { name: 'Slim Ben Amor',     position: 'DM', rating: 71 },
      { name: 'Youssef Chibah',    position: 'CM', rating: 71 },
      { name: 'Skander Souayah',   position: 'RW', rating: 71 },
      { name: 'Ziad Jaziri',       position: 'ST', rating: 72 },
      { name: 'Mehdi Ben Slimane', position: 'LW', rating: 70 },
    ],
  },
  'tunesien:2002': {
    formation: '4-4-2', teamLabel: 'Túnez (2002)',
    source: 'Tunisia - World Cup 2002',
    ratings: { attack: 72, midfield: 71, defense: 71, goalkeeping: 70 },
    players: [
      { name: 'Chokri El Ouaer',   position: 'GK', rating: 70 },
      { name: 'Mhamed Trabelsi',   position: 'RB', rating: 73 },
      { name: 'Hatem Trabelsi',    position: 'LB', rating: 74 },
      { name: 'Radhi Jaïdi',       position: 'CB', rating: 75 },
      { name: 'Khaled Badra',      position: 'CB', rating: 71 },
      { name: 'Slim Ben Amor',     position: 'DM', rating: 72 },
      { name: 'Raouf Bouzaiene',   position: 'CM', rating: 71 },
      { name: 'Adel Sellimi',      position: 'CM', rating: 73 },
      { name: 'Santos',            position: 'RW', rating: 72 },
      { name: 'Ziad Jaziri',       position: 'ST', rating: 73 },
      { name: 'Imed Mhedhebi',     position: 'LW', rating: 71 },
    ],
  },
  'tunesien:2006': {
    formation: '4-4-2', teamLabel: 'Túnez (2006)',
    source: 'Tunisia - World Cup 2006',
    ratings: { attack: 71, midfield: 71, defense: 72, goalkeeping: 70 },
    players: [
      { name: 'Ali Boumnijel',     position: 'GK', rating: 71 },
      { name: 'Hatem Trabelsi',    position: 'RB', rating: 74 },
      { name: 'Radhi Jaïdi',       position: 'CB', rating: 76 },
      { name: 'Anis Ayari',        position: 'CB', rating: 71 },
      { name: 'Karim Haggui',      position: 'LB', rating: 73 },
      { name: 'Jawhar Mnari',      position: 'DM', rating: 72 },
      { name: 'Mehdi Nafti',       position: 'CM', rating: 72 },
      { name: 'Oussama Darragi',   position: 'CM', rating: 71 },
      { name: 'Hocine Ragued',     position: 'RW', rating: 71 },
      { name: 'Ziad Jaziri',       position: 'ST', rating: 73 },
      { name: 'Chaouki Ben Saada', position: 'LW', rating: 72 },
    ],
  },
  'tunesien:2018': {
    formation: '4-3-3', teamLabel: 'Túnez (2018)',
    source: 'Tunisia - World Cup 2018',
    ratings: { attack: 72, midfield: 71, defense: 71, goalkeeping: 70 },
    players: [
      { name: 'Mouez Hassen',      position: 'GK', rating: 71 },
      { name: 'Dylan Bronn',       position: 'CB', rating: 72 },
      { name: 'Syam Ben Youssef',  position: 'CB', rating: 72 },
      { name: 'Yassine Meriah',    position: 'RB', rating: 71 },
      { name: 'Ali Maaloul',       position: 'LB', rating: 74 },
      { name: 'Ellyes Skhiri',     position: 'DM', rating: 74 },
      { name: 'Ferjani Sassi',     position: 'CM', rating: 74 },
      { name: 'Anice Badri',       position: 'CM', rating: 72 },
      { name: 'Wahbi Khazri',      position: 'AM', rating: 76 },
      { name: 'Fakhreddine Ben Youssef', position: 'ST', rating: 71 },
      { name: 'Naïm Sliti',        position: 'LW', rating: 72 },
    ],
  },
  'tunesien:2022': {
    formation: '4-3-3', teamLabel: 'Túnez (2022)',
    source: 'Tunisia - World Cup 2022',
    ratings: { attack: 73, midfield: 72, defense: 73, goalkeeping: 71 },
    players: [
      { name: 'Aymen Dahmen',      position: 'GK', rating: 72 },
      { name: 'Montassar Talbi',   position: 'CB', rating: 73 },
      { name: 'Dylan Bronn',       position: 'CB', rating: 73 },
      { name: 'Wajdi Kechrida',    position: 'RB', rating: 72 },
      { name: 'Ali Maaloul',       position: 'LB', rating: 74 },
      { name: 'Ellyes Skhiri',     position: 'DM', rating: 76 },
      { name: 'Aissa Laidouni',    position: 'CM', rating: 73 },
      { name: 'Ferjani Sassi',     position: 'CM', rating: 73 },
      { name: 'Wahbi Khazri',      position: 'AM', rating: 75 },
      { name: 'Youssef Msakni',    position: 'LW', rating: 74 },
      { name: 'Seifeddine Jaziri', position: 'ST', rating: 72 },
    ],
  },

  // ── JAPAN ─────────────────────────────────────────────────────────────
  'japan:1998': {
    formation: '4-4-2', teamLabel: 'Japón (1998)',
    source: 'Japan - World Cup 1998 (debut)',
    ratings: { attack: 70, midfield: 70, defense: 68, goalkeeping: 68 },
    players: [
      { name: 'Yoshikatsu Kawaguchi', position: 'GK', rating: 69 },
      { name: 'Naoki Soma',        position: 'RB', rating: 68 },
      { name: 'Masami Ihara',      position: 'CB', rating: 70 },
      { name: 'Akira Narahashi',   position: 'CB', rating: 68 },
      { name: 'Norio Omura',       position: 'LB', rating: 68 },
      { name: 'Hidetoshi Nakata',  position: 'CM', rating: 76 },
      { name: 'Masashi Nakayama',  position: 'AM', rating: 72 },
      { name: 'Motohiro Yamaguchi', position: 'DM', rating: 69 },
      { name: 'Shinji Ono',        position: 'CM', rating: 70 },
      { name: 'Shunsuke Nakamura', position: 'RW', rating: 71 },
      { name: 'Takuya Takagi',     position: 'ST', rating: 69 },
    ],
  },
  'japan:2002': {
    formation: '4-4-2', teamLabel: 'Japón (2002)',
    source: 'Japan - World Cup 2002 (co-host, QF)',
    ratings: { attack: 75, midfield: 74, defense: 73, goalkeeping: 72 },
    players: [
      { name: 'Yoshikatsu Kawaguchi', position: 'GK', rating: 73 },
      { name: 'Koji Nakata',       position: 'RB', rating: 72 },
      { name: 'Tsuneyasu Miyamoto', position: 'CB', rating: 74 },
      { name: 'Santos',            position: 'CB', rating: 73 },
      { name: 'Ryuzo Morioka',     position: 'LB', rating: 71 },
      { name: 'Hidetoshi Nakata',  position: 'CM', rating: 78 },
      { name: 'Shinji Ono',        position: 'CM', rating: 74 },
      { name: 'Junichi Inamoto',   position: 'DM', rating: 74 },
      { name: 'Shunsuke Nakamura', position: 'RW', rating: 75 },
      { name: 'Takayuki Suzuki',   position: 'ST', rating: 73 },
      { name: 'Atsushi Yanagisawa', position: 'ST', rating: 72 },
    ],
  },
  'japan:2006': {
    formation: '4-3-3', teamLabel: 'Japón (2006)',
    source: 'Japan - World Cup 2006',
    ratings: { attack: 72, midfield: 72, defense: 70, goalkeeping: 70 },
    players: [
      { name: 'Yoshikatsu Kawaguchi', position: 'GK', rating: 71 },
      { name: 'Yuichi Komano',     position: 'RB', rating: 71 },
      { name: 'Tsuneyasu Miyamoto', position: 'CB', rating: 72 },
      { name: 'Marcus Tulio Tanaka', position: 'CB', rating: 70 },
      { name: 'Akira Kaji',        position: 'LB', rating: 70 },
      { name: 'Hidetoshi Nakata',  position: 'CM', rating: 75 },
      { name: 'Shunsuke Nakamura', position: 'CM', rating: 75 },
      { name: 'Shinji Ono',        position: 'DM', rating: 72 },
      { name: 'Koji Nakata',       position: 'RW', rating: 71 },
      { name: 'Seiichiro Maki',    position: 'ST', rating: 71 },
      { name: 'Masashi Oguro',     position: 'LW', rating: 72 },
    ],
  },
  'japan:2010': {
    formation: '4-4-2', teamLabel: 'Japón (2010)',
    source: 'Japan - World Cup 2010 (R16)',
    ratings: { attack: 73, midfield: 73, defense: 72, goalkeeping: 72 },
    players: [
      { name: 'Eiji Kawashima',    position: 'GK', rating: 73 },
      { name: 'Yuto Nagatomo',     position: 'LB', rating: 75 },
      { name: 'Tulio Tanaka',      position: 'CB', rating: 72 },
      { name: 'Maya Yoshida',      position: 'CB', rating: 73 },
      { name: 'Atsuto Uchida',     position: 'RB', rating: 73 },
      { name: 'Yasuhito Endo',     position: 'DM', rating: 76 },
      { name: 'Shunsuke Nakamura', position: 'CM', rating: 74 },
      { name: 'Makoto Hasebe',     position: 'CM', rating: 74 },
      { name: 'Daisuke Matsui',    position: 'RW', rating: 72 },
      { name: 'Shinji Okazaki',    position: 'ST', rating: 73 },
      { name: 'Keisuke Honda',     position: 'AM', rating: 78 },
    ],
  },
  'japan:2014': {
    formation: '4-2-3-1', teamLabel: 'Japón (2014)',
    source: 'Japan - World Cup 2014',
    ratings: { attack: 73, midfield: 73, defense: 72, goalkeeping: 72 },
    players: [
      { name: 'Eiji Kawashima',    position: 'GK', rating: 73 },
      { name: 'Atsuto Uchida',     position: 'RB', rating: 74 },
      { name: 'Maya Yoshida',      position: 'CB', rating: 74 },
      { name: 'Masahiko Inoha',    position: 'CB', rating: 71 },
      { name: 'Yuto Nagatomo',     position: 'LB', rating: 75 },
      { name: 'Makoto Hasebe',     position: 'DM', rating: 75 },
      { name: 'Yasuhito Endo',     position: 'DM', rating: 75 },
      { name: 'Keisuke Honda',     position: 'AM', rating: 79 },
      { name: 'Shinji Kagawa',     position: 'AM', rating: 79 },
      { name: 'Shinji Okazaki',    position: 'ST', rating: 74 },
      { name: 'Yoshito Okubo',     position: 'LW', rating: 73 },
    ],
  },
  'japan:2018': {
    formation: '4-2-3-1', teamLabel: 'Japón (2018)',
    source: 'Japan - World Cup 2018 (R16)',
    ratings: { attack: 74, midfield: 74, defense: 73, goalkeeping: 73 },
    players: [
      { name: 'Eiji Kawashima',    position: 'GK', rating: 73 },
      { name: 'Hiroki Sakai',      position: 'RB', rating: 74 },
      { name: 'Maya Yoshida',      position: 'CB', rating: 75 },
      { name: 'Gen Shoji',         position: 'CB', rating: 72 },
      { name: 'Yuto Nagatomo',     position: 'LB', rating: 74 },
      { name: 'Makoto Hasebe',     position: 'DM', rating: 75 },
      { name: 'Gaku Shibasaki',    position: 'DM', rating: 73 },
      { name: 'Keisuke Honda',     position: 'AM', rating: 77 },
      { name: 'Shinji Kagawa',     position: 'AM', rating: 77 },
      { name: 'Shinji Okazaki',    position: 'ST', rating: 73 },
      { name: 'Takashi Inui',      position: 'LW', rating: 74 },
    ],
  },
  'japan:2022': {
    formation: '4-3-3', teamLabel: 'Japón (2022)',
    source: 'Japan - World Cup 2022 (R16, beat Germany & Spain)',
    ratings: { attack: 77, midfield: 76, defense: 76, goalkeeping: 75 },
    players: [
      { name: 'Shuichi Gonda',     position: 'GK', rating: 75 },
      { name: 'Hiroki Sakai',      position: 'RB', rating: 74 },
      { name: 'Maya Yoshida',      position: 'CB', rating: 75 },
      { name: 'Ko Itakura',        position: 'CB', rating: 76 },
      { name: 'Yuto Nagatomo',     position: 'LB', rating: 73 },
      { name: 'Wataru Endo',       position: 'DM', rating: 77 },
      { name: 'Ritsu Doan',        position: 'CM', rating: 77 },
      { name: 'Junya Ito',         position: 'RW', rating: 77 },
      { name: 'Takefusa Kubo',     position: 'AM', rating: 78 },
      { name: 'Kaoru Mitoma',      position: 'LW', rating: 79 },
      { name: 'Daizen Maeda',      position: 'ST', rating: 74 },
    ],
  },

  // ── SAUDI-ARABIEN ─────────────────────────────────────────────────────
  'saudi-arabien:1994': {
    formation: '4-4-2', teamLabel: 'Arabia Saudí (1994)',
    source: 'Saudi Arabia - World Cup 1994 (R16)',
    ratings: { attack: 77, midfield: 75, defense: 73, goalkeeping: 72 },
    players: [
      { name: 'Mohamed Al-Deayea', position: 'GK', rating: 74 },
      { name: 'Abdulwahab Nasser', position: 'RB', rating: 73 },
      { name: 'Youssef Al-Thunayan', position: 'CB', rating: 73 },
      { name: 'Mohammed Al-Yaami', position: 'CB', rating: 73 },
      { name: 'Ahmed Madani',      position: 'LB', rating: 72 },
      { name: 'Fahad Al-Bishi',    position: 'DM', rating: 73 },
      { name: 'Khamees Al-Owairan', position: 'CM', rating: 77 },
      { name: 'Fuad Anwar',        position: 'CM', rating: 73 },
      { name: 'Sami Al-Jaber',     position: 'AM', rating: 78 },
      { name: 'Saeed Al-Owairan',  position: 'ST', rating: 81 },
      { name: 'Yasser Al-Qahtani', position: 'LW', rating: 73 },
    ],
  },
  'saudi-arabien:1998': {
    formation: '4-4-2', teamLabel: 'Arabia Saudí (1998)',
    source: 'Saudi Arabia - World Cup 1998',
    ratings: { attack: 73, midfield: 72, defense: 71, goalkeeping: 72 },
    players: [
      { name: 'Mohamed Al-Deayea', position: 'GK', rating: 74 },
      { name: 'Amin Beinker',      position: 'RB', rating: 71 },
      { name: 'Youssef Al-Thunayan', position: 'CB', rating: 72 },
      { name: 'Hussein Sulimani',  position: 'CB', rating: 71 },
      { name: 'Ahmed Dokhi',       position: 'LB', rating: 71 },
      { name: 'Mohamed Khojah',    position: 'DM', rating: 71 },
      { name: 'Sami Al-Jaber',     position: 'CM', rating: 77 },
      { name: 'Mustafa Al-Wahsh',  position: 'CM', rating: 71 },
      { name: 'Fuad Anwar',        position: 'RW', rating: 72 },
      { name: 'Fawzi Al-Thunayan', position: 'ST', rating: 72 },
      { name: 'Fahad Al-Mehalel',  position: 'LW', rating: 72 },
    ],
  },
  'saudi-arabien:2002': {
    formation: '4-4-2', teamLabel: 'Arabia Saudí (2002)',
    source: 'Saudi Arabia - World Cup 2002',
    ratings: { attack: 71, midfield: 70, defense: 69, goalkeeping: 71 },
    players: [
      { name: 'Mohamed Al-Deayea', position: 'GK', rating: 73 },
      { name: 'Omar Al-Ghamdi',    position: 'RB', rating: 69 },
      { name: 'Redha Tukar',       position: 'CB', rating: 70 },
      { name: 'Mohammed Al-Shlhoub', position: 'CB', rating: 70 },
      { name: 'Abdelslam Khathran', position: 'LB', rating: 69 },
      { name: 'Ahmed Al-Dokhi',    position: 'DM', rating: 70 },
      { name: 'Sami Al-Jaber',     position: 'CM', rating: 74 },
      { name: 'Nawaf Al-Temyat',   position: 'CM', rating: 72 },
      { name: 'Yasser Al-Qahtani', position: 'RW', rating: 72 },
      { name: 'Mohammed Noor',     position: 'ST', rating: 70 },
      { name: 'Abdullah Al-Dosari', position: 'LW', rating: 69 },
    ],
  },
  'saudi-arabien:2006': {
    formation: '4-4-2', teamLabel: 'Arabia Saudí (2006)',
    source: 'Saudi Arabia - World Cup 2006',
    ratings: { attack: 70, midfield: 69, defense: 69, goalkeeping: 70 },
    players: [
      { name: 'Mabrouk Zaid',      position: 'GK', rating: 70 },
      { name: 'Hussein Abd Robou', position: 'RB', rating: 69 },
      { name: 'Mohammed Zubromawi', position: 'CB', rating: 70 },
      { name: 'Hamad Al-Montashari', position: 'CB', rating: 71 },
      { name: 'Abdullah Jumaan',   position: 'LB', rating: 69 },
      { name: 'Mohammed Al-Anbar', position: 'DM', rating: 69 },
      { name: 'Sami Al-Jaber',     position: 'CM', rating: 72 },
      { name: 'Yasser Al-Qahtani', position: 'CM', rating: 73 },
      { name: 'Ahmed Al-Bahri',    position: 'RW', rating: 70 },
      { name: 'Saud Khariri',      position: 'ST', rating: 70 },
      { name: 'Abdullah Al-Ghreiz', position: 'LW', rating: 69 },
    ],
  },

  // ── SENEGAL ───────────────────────────────────────────────────────────
  'senegal:2002': {
    formation: '4-4-2', teamLabel: 'Senegal (2002)',
    source: 'Senegal - World Cup 2002 (QF, beat France)',
    ratings: { attack: 79, midfield: 77, defense: 76, goalkeeping: 75 },
    players: [
      { name: 'Tony Sylva',        position: 'GK', rating: 76 },
      { name: 'Omar Daf',          position: 'RB', rating: 75 },
      { name: 'Lamine Diatta',     position: 'CB', rating: 76 },
      { name: 'Ferdinand Coly',    position: 'LB', rating: 77 },
      { name: 'Pape Sarr',         position: 'CB', rating: 75 },
      { name: 'Aliou Cissé',       position: 'DM', rating: 77 },
      { name: 'Salif Diao',        position: 'CM', rating: 76 },
      { name: 'Pape Bouba Diop',   position: 'CM', rating: 78 },
      { name: 'El Hadji Diouf',    position: 'RW', rating: 81 },
      { name: 'Henri Camara',      position: 'ST', rating: 78 },
      { name: 'Khalilou Fadiga',   position: 'LW', rating: 77 },
    ],
  },
  'senegal:2018': {
    formation: '4-4-2', teamLabel: 'Senegal (2018)',
    source: 'Senegal - World Cup 2018',
    ratings: { attack: 77, midfield: 75, defense: 74, goalkeeping: 73 },
    players: [
      { name: 'Khadim N\'Diaye',   position: 'GK', rating: 74 },
      { name: 'Youssouf Sabaly',   position: 'RB', rating: 74 },
      { name: 'Salif Sané',        position: 'CB', rating: 75 },
      { name: 'Cheikh Koulibaly',  position: 'CB', rating: 77 },
      { name: 'Saliou Ciss',       position: 'LB', rating: 73 },
      { name: 'Idrissa Gueye',     position: 'DM', rating: 79 },
      { name: 'Cheikhou Kouyaté',  position: 'CM', rating: 76 },
      { name: 'Alfred Ndiaye',     position: 'CM', rating: 74 },
      { name: 'Moussa Wagué',      position: 'RW', rating: 74 },
      { name: 'Sadio Mané',        position: 'LW', rating: 87 },
      { name: 'M\'Baye Niang',     position: 'ST', rating: 75 },
    ],
  },
  'senegal:2022': {
    formation: '4-3-3', teamLabel: 'Senegal (2022)',
    source: 'Senegal - World Cup 2022 (R16, AFCON holders)',
    ratings: { attack: 79, midfield: 78, defense: 76, goalkeeping: 75 },
    players: [
      { name: 'Édouard Mendy',     position: 'GK', rating: 82 },
      { name: 'Bouna Sarr',        position: 'RB', rating: 74 },
      { name: 'Kalidou Koulibaly', position: 'CB', rating: 83 },
      { name: 'Abdou Diallo',      position: 'CB', rating: 76 },
      { name: 'Fodé Ballo-Touré',  position: 'LB', rating: 73 },
      { name: 'Idrissa Gueye',     position: 'DM', rating: 78 },
      { name: 'Cheikhou Kouyaté',  position: 'CM', rating: 74 },
      { name: 'Nampalys Mendy',    position: 'CM', rating: 73 },
      { name: 'Ismaïla Sarr',      position: 'RW', rating: 80 },
      { name: 'Sadio Mané',        position: 'LW', rating: 87 },
      { name: 'Boulaye Dia',       position: 'ST', rating: 76 },
    ],
  },

  // ── TÜRKEI ────────────────────────────────────────────────────────────
  'turkei:2002': {
    formation: '4-4-2', teamLabel: 'Turquía (2002)',
    source: 'Turkey - World Cup 2002 (3rd place!)',
    ratings: { attack: 81, midfield: 79, defense: 78, goalkeeping: 77 },
    players: [
      { name: 'Rüştü Reçber',      position: 'GK', rating: 79 },
      { name: 'Fatih Akyel',       position: 'RB', rating: 77 },
      { name: 'Alpay Özalan',      position: 'CB', rating: 79 },
      { name: 'Bülent Korkmaz',    position: 'CB', rating: 79 },
      { name: 'Tayfur Havutçu',    position: 'LB', rating: 76 },
      { name: 'Emre Belözoğlu',    position: 'CM', rating: 81 },
      { name: 'Tugay Kerimoğlu',   position: 'DM', rating: 80 },
      { name: 'Yıldıray Baştürk',  position: 'CM', rating: 78 },
      { name: 'Hasan Şaş',         position: 'RW', rating: 78 },
      { name: 'Hakan Şükür',       position: 'ST', rating: 83 },
      { name: 'İlhan Mansız',      position: 'LW', rating: 79 },
    ],
  },

  // ── VEREINIGTE STAATEN ────────────────────────────────────────────────
  'vereinigte-staaten:1994': {
    formation: '4-4-2', teamLabel: 'USA (1994)',
    source: 'USA - World Cup 1994 (host, QF)',
    ratings: { attack: 74, midfield: 73, defense: 74, goalkeeping: 73 },
    players: [
      { name: 'Tony Meola',        position: 'GK', rating: 74 },
      { name: 'Thomas Dooley',     position: 'CB', rating: 74 },
      { name: 'Alexi Lalas',       position: 'CB', rating: 74 },
      { name: 'Paul Caligiuri',    position: 'RB', rating: 73 },
      { name: 'Mike Burns',        position: 'LB', rating: 72 },
      { name: 'Tab Ramos',         position: 'CM', rating: 75 },
      { name: 'John Harkes',       position: 'CM', rating: 74 },
      { name: 'Fernando Clavijo',  position: 'DM', rating: 72 },
      { name: 'Ernie Stewart',     position: 'RW', rating: 74 },
      { name: 'Roy Wegerle',       position: 'AM', rating: 73 },
      { name: 'Eric Wynalda',      position: 'ST', rating: 76 },
    ],
  },
  'vereinigte-staaten:1998': {
    formation: '4-4-2', teamLabel: 'USA (1998)',
    source: 'USA - World Cup 1998',
    ratings: { attack: 70, midfield: 70, defense: 70, goalkeeping: 70 },
    players: [
      { name: 'Kasey Keller',      position: 'GK', rating: 71 },
      { name: 'Frankie Hejduk',    position: 'RB', rating: 70 },
      { name: 'Alexi Lalas',       position: 'CB', rating: 72 },
      { name: 'Jeff Agoos',        position: 'CB', rating: 71 },
      { name: 'Eddie Pope',        position: 'LB', rating: 71 },
      { name: 'Tab Ramos',         position: 'CM', rating: 72 },
      { name: 'John Harkes',       position: 'CM', rating: 71 },
      { name: 'Brian Maisonneuve', position: 'DM', rating: 69 },
      { name: 'Earnie Stewart',    position: 'RW', rating: 72 },
      { name: 'Brian McBride',     position: 'ST', rating: 72 },
      { name: 'Eric Wynalda',      position: 'LW', rating: 73 },
    ],
  },
  'vereinigte-staaten:2002': {
    formation: '4-4-2', teamLabel: 'USA (2002)',
    source: 'USA - World Cup 2002 (QF)',
    ratings: { attack: 74, midfield: 73, defense: 74, goalkeeping: 72 },
    players: [
      { name: 'Brad Friedel',      position: 'GK', rating: 74 },
      { name: 'Frankie Hejduk',    position: 'RB', rating: 72 },
      { name: 'Tony Sanneh',       position: 'CB', rating: 72 },
      { name: 'Carlos Bocanegra',  position: 'CB', rating: 74 },
      { name: 'Eddie Pope',        position: 'LB', rating: 73 },
      { name: 'Claudio Reyna',     position: 'CM', rating: 76 },
      { name: 'DaMarcus Beasley',  position: 'CM', rating: 74 },
      { name: 'Pablo Mastroeni',   position: 'DM', rating: 73 },
      { name: 'Landon Donovan',    position: 'AM', rating: 78 },
      { name: 'Brian McBride',     position: 'ST', rating: 75 },
      { name: 'Josh Wolff',        position: 'LW', rating: 72 },
    ],
  },
  'vereinigte-staaten:2006': {
    formation: '4-4-2', teamLabel: 'USA (2006)',
    source: 'USA - World Cup 2006',
    ratings: { attack: 71, midfield: 71, defense: 71, goalkeeping: 72 },
    players: [
      { name: 'Kasey Keller',      position: 'GK', rating: 73 },
      { name: 'Steve Cherundolo',  position: 'RB', rating: 72 },
      { name: 'Oguchi Onyewu',     position: 'CB', rating: 74 },
      { name: 'Carlos Bocanegra',  position: 'CB', rating: 73 },
      { name: 'Eddie Lewis',       position: 'LB', rating: 71 },
      { name: 'Claudio Reyna',     position: 'CM', rating: 74 },
      { name: 'Pablo Mastroeni',   position: 'DM', rating: 72 },
      { name: 'DaMarcus Beasley',  position: 'RW', rating: 73 },
      { name: 'Landon Donovan',    position: 'AM', rating: 77 },
      { name: 'Brian McBride',     position: 'ST', rating: 74 },
      { name: 'Ben Olsen',         position: 'LW', rating: 70 },
    ],
  },
  'vereinigte-staaten:2010': {
    formation: '4-4-2', teamLabel: 'USA (2010)',
    source: 'USA - World Cup 2010 (R16)',
    ratings: { attack: 73, midfield: 73, defense: 73, goalkeeping: 73 },
    players: [
      { name: 'Tim Howard',        position: 'GK', rating: 77 },
      { name: 'Steve Cherundolo',  position: 'RB', rating: 73 },
      { name: 'Jay DeMerit',       position: 'CB', rating: 72 },
      { name: 'Oguchi Onyewu',     position: 'CB', rating: 74 },
      { name: 'Carlos Bocanegra',  position: 'LB', rating: 73 },
      { name: 'Maurice Edu',       position: 'DM', rating: 72 },
      { name: 'Michael Bradley',   position: 'CM', rating: 75 },
      { name: 'Clint Dempsey',     position: 'CM', rating: 79 },
      { name: 'Landon Donovan',    position: 'AM', rating: 79 },
      { name: 'Jozy Altidore',     position: 'ST', rating: 75 },
      { name: 'DaMarcus Beasley',  position: 'LW', rating: 72 },
    ],
  },
  'vereinigte-staaten:2014': {
    formation: '4-4-2', teamLabel: 'USA (2014)',
    source: 'USA - World Cup 2014 (R16)',
    ratings: { attack: 73, midfield: 73, defense: 73, goalkeeping: 75 },
    players: [
      { name: 'Tim Howard',        position: 'GK', rating: 79 },
      { name: 'DeAndre Yedlin',    position: 'RB', rating: 73 },
      { name: 'Geoff Cameron',     position: 'CB', rating: 74 },
      { name: 'Matt Besler',       position: 'CB', rating: 73 },
      { name: 'DaMarcus Beasley',  position: 'LB', rating: 72 },
      { name: 'Michael Bradley',   position: 'DM', rating: 75 },
      { name: 'Kyle Beckerman',    position: 'DM', rating: 72 },
      { name: 'Clint Dempsey',     position: 'AM', rating: 78 },
      { name: 'Alejandro Bedoya',  position: 'CM', rating: 72 },
      { name: 'Jozy Altidore',     position: 'ST', rating: 74 },
      { name: 'Aron Jóhannsson',   position: 'LW', rating: 72 },
    ],
  },
};

// ─── APPLY STUBS TO SQUAD FILES ──────────────────────────────────────────────
let added = 0, skipped = 0;
const results = {};

for (const [key, stub] of Object.entries(STUBS)) {
  const [slug, year] = key.split(':');
  const filePath = path.join(__dirname, 'squads', slug + '.json');
  if (!fs.existsSync(filePath)) {
    console.warn('  ⚠️  File not found:', filePath);
    continue;
  }
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  if (!data.seasons) data.seasons = {};

  if (data.seasons[year]) {
    skipped++;
    if (!results[slug]) results[slug] = [];
    results[slug].push(year + ' (already exists, skipped)');
    continue;
  }

  data.seasons[year] = stub;
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  added++;
  if (!results[slug]) results[slug] = [];
  results[slug].push(year + ' ✅');
}

console.log('\n=== RESULTS ===');
for (const [slug, years] of Object.entries(results).sort()) {
  console.log(slug + ':  ' + years.join(', '));
}
console.log('\nAdded:', added, '| Skipped (already existed):', skipped);
