'use strict';
// Creates squad JSON files for the 19 Libertadores teams missing from the catalog
const fs   = require('fs');
const path = require('path');

const SQUADS_DIR = path.join(__dirname, 'squads');

const TEAMS = [
  {
    slug: 'bolivar', name: 'Club Bolívar', group: '🌎 América del Sur',
    ratings: { attack: 79, midfield: 79, defense: 78, goalkeeping: 77 },
    formation: '4-3-3',
    players: [
      { name: 'Guillermo Viscarra',  position: 'GK', rating: 77 },
      { name: 'José Sagredo',        position: 'CB', rating: 78 },
      { name: 'Jesús Sagredo',       position: 'CB', rating: 77 },
      { name: 'Gustavo Méndez',      position: 'RB', rating: 76 },
      { name: 'Jairo Quinteros',     position: 'LB', rating: 75 },
      { name: 'Leonel Justiniano',   position: 'DM', rating: 79 },
      { name: 'Ramiro Vaca',         position: 'CM', rating: 80 },
      { name: 'Stiven Banguero',     position: 'CM', rating: 78 },
      { name: 'Jeyson Chura',        position: 'LW', rating: 79 },
      { name: 'Rodrigo Ramallo',     position: 'ST', rating: 81 },
      { name: 'Marcio Pereyra',      position: 'RW', rating: 79 },
      { name: 'Daniel Vaca',         position: 'GK', rating: 73 },
      { name: 'Jorge Flores',        position: 'CB', rating: 75 },
      { name: 'Diego Bejarano',      position: 'CM', rating: 76 },
      { name: 'Adrián Montaño',      position: 'ST', rating: 76 },
      { name: 'Miguel Moreira',      position: 'LW', rating: 75 },
    ],
    source: 'Transfermarkt — Club Bolívar (2025/2026)', teamLabel: 'Bolívar (2025–26)',
  },
  {
    slug: 'ldu-quito', name: 'Liga Deportiva Universitaria de Quito', group: '🌎 América del Sur',
    ratings: { attack: 82, midfield: 81, defense: 80, goalkeeping: 79 },
    formation: '4-2-3-1',
    players: [
      { name: 'Alexander Domínguez', position: 'GK', rating: 81 },
      { name: 'Cristian Cruz',       position: 'CB', rating: 80 },
      { name: 'Lautaro Díaz',        position: 'CB', rating: 79 },
      { name: 'Nilson Angulo',       position: 'RB', rating: 78 },
      { name: 'Luis Miranda',        position: 'LB', rating: 77 },
      { name: 'Luis Caicedo',        position: 'DM', rating: 81 },
      { name: 'Anderson Ordóñez',    position: 'DM', rating: 79 },
      { name: 'Jean Sánchez',        position: 'AM', rating: 82 },
      { name: 'Jhojan Julio',        position: 'RW', rating: 80 },
      { name: 'Carlos Rodríguez',    position: 'LW', rating: 80 },
      { name: 'Lisandro Alzugaray',  position: 'ST', rating: 82 },
      { name: 'Eduardo Espinoza',    position: 'GK', rating: 74 },
      { name: 'Jorge Pinos',         position: 'CB', rating: 76 },
      { name: 'Diego Caicedo',       position: 'CM', rating: 78 },
      { name: 'Pablo Marini',        position: 'ST', rating: 78 },
    ],
    source: 'Transfermarkt — LDU Quito (2025/2026)', teamLabel: 'LDU Quito (2025–26)',
  },
  {
    slug: 'independiente-del-valle', name: 'Independiente del Valle', group: '🌎 América del Sur',
    ratings: { attack: 81, midfield: 81, defense: 79, goalkeeping: 78 },
    formation: '4-3-3',
    players: [
      { name: 'Moisés Ramírez',      position: 'GK', rating: 79 },
      { name: 'Miler Bolaños',       position: 'RB', rating: 79 },
      { name: 'Juan Carlos Paredes', position: 'CB', rating: 79 },
      { name: 'Óscar Murillo',       position: 'CB', rating: 79 },
      { name: 'Diego Guamangate',    position: 'LB', rating: 77 },
      { name: 'Alan Franco',         position: 'DM', rating: 81 },
      { name: 'Jhon Sánchez',        position: 'CM', rating: 80 },
      { name: 'Ezequiel Piovi',      position: 'CM', rating: 79 },
      { name: 'Kevin Minda',         position: 'RW', rating: 80 },
      { name: 'Alexander Alvarado',  position: 'LW', rating: 81 },
      { name: 'Jonatan Álvez',       position: 'ST', rating: 82 },
      { name: 'Sebastián Pérez',     position: 'GK', rating: 74 },
      { name: 'Paul Caicedo',        position: 'CB', rating: 76 },
      { name: 'Jáder Obrian',        position: 'LW', rating: 78 },
      { name: 'Renato Ibarra',       position: 'AM', rating: 79 },
    ],
    source: 'Transfermarkt — Independiente del Valle (2025/2026)', teamLabel: 'Ind. del Valle (2025–26)',
  },
  {
    slug: 'barcelona-sc', name: 'Barcelona SC', group: '🌎 América del Sur',
    ratings: { attack: 78, midfield: 77, defense: 76, goalkeeping: 76 },
    formation: '4-4-2',
    players: [
      { name: 'Javier Burrai',       position: 'GK', rating: 76 },
      { name: 'Carlos Garcés',       position: 'RB', rating: 76 },
      { name: 'Adonis Preciado',     position: 'CB', rating: 77 },
      { name: 'Xavier Mejía',        position: 'CB', rating: 76 },
      { name: 'Jesús Rodríguez',     position: 'LB', rating: 75 },
      { name: 'Joffre Escobar',      position: 'CM', rating: 77 },
      { name: 'Carlos Vera',         position: 'CM', rating: 76 },
      { name: 'Damián Díaz',         position: 'AM', rating: 79 },
      { name: 'Bryan Angulo',        position: 'RW', rating: 78 },
      { name: 'Fidel Martínez',      position: 'ST', rating: 79 },
      { name: 'Jonatan Álvez',       position: 'ST', rating: 78 },
      { name: 'Wellington Sancho',   position: 'GK', rating: 73 },
      { name: 'Gabriel Cortez',      position: 'CB', rating: 74 },
      { name: 'Ariel Moran',         position: 'CM', rating: 75 },
      { name: 'Joao Ortiz',          position: 'ST', rating: 75 },
    ],
    source: 'Transfermarkt — Barcelona SC (2025/2026)', teamLabel: 'Barcelona SC (2025–26)',
  },
  {
    slug: 'universitario', name: 'Club Universitario de Deportes', group: '🌎 América del Sur',
    ratings: { attack: 78, midfield: 77, defense: 76, goalkeeping: 75 },
    formation: '4-3-3',
    players: [
      { name: 'Diego Romero',        position: 'GK', rating: 76 },
      { name: 'Gustavo Dulanto',     position: 'CB', rating: 77 },
      { name: 'Nelson Cabanillas',   position: 'CB', rating: 76 },
      { name: 'Aldo Corzo',          position: 'RB', rating: 77 },
      { name: 'Segundo Portocarrero',position: 'LB', rating: 75 },
      { name: 'Rodrigo Ureña',       position: 'DM', rating: 78 },
      { name: 'Manuel Barreto',      position: 'CM', rating: 77 },
      { name: 'Andy Polo',           position: 'CM', rating: 78 },
      { name: 'Piero Quispe',        position: 'AM', rating: 80 },
      { name: 'Alex Valera',         position: 'ST', rating: 79 },
      { name: 'Edison Flores',       position: 'LW', rating: 79 },
      { name: 'José Carvallo',       position: 'GK', rating: 73 },
      { name: 'Brayan Velarde',      position: 'CB', rating: 74 },
      { name: 'Martín Pérez Guedes', position: 'CM', rating: 76 },
      { name: 'Brenner',             position: 'ST', rating: 77 },
    ],
    source: 'Transfermarkt — Universitario de Deportes (2025/2026)', teamLabel: 'Universitario (2025–26)',
  },
  {
    slug: 'sporting-cristal', name: 'Club Sporting Cristal', group: '🌎 América del Sur',
    ratings: { attack: 77, midfield: 76, defense: 75, goalkeeping: 74 },
    formation: '4-3-3',
    players: [
      { name: 'Renato Solís',        position: 'GK', rating: 75 },
      { name: 'Johan Madrid',        position: 'RB', rating: 75 },
      { name: 'Omar Merlo',          position: 'CB', rating: 76 },
      { name: 'Gino Peruzzi',        position: 'CB', rating: 77 },
      { name: 'Nilson Loyola',       position: 'LB', rating: 74 },
      { name: 'Jesús Pretell',       position: 'DM', rating: 76 },
      { name: 'Christofer Gonzales', position: 'CM', rating: 78 },
      { name: 'Joao Grimaldo',       position: 'CM', rating: 77 },
      { name: 'Percy Liza',          position: 'RW', rating: 76 },
      { name: 'Irven Ávila',         position: 'ST', rating: 78 },
      { name: 'Alejandro Hohberg',   position: 'LW', rating: 77 },
      { name: 'Christopher Olivares',position: 'GK', rating: 72 },
      { name: 'Renzo Garcés',        position: 'CB', rating: 73 },
      { name: 'Martín Távara',       position: 'AM', rating: 76 },
      { name: 'Lenyn Güenaga',       position: 'ST', rating: 75 },
    ],
    source: 'Transfermarkt — Sporting Cristal (2025/2026)', teamLabel: 'Sporting Cristal (2025–26)',
  },
  {
    slug: 'cusco-fc', name: 'Cusco FC', group: '🌎 América del Sur',
    ratings: { attack: 74, midfield: 74, defense: 73, goalkeeping: 72 },
    formation: '4-4-2',
    players: [
      { name: 'Ángel Zamora',        position: 'GK', rating: 73 },
      { name: 'Wilber Cartagena',    position: 'RB', rating: 73 },
      { name: 'Alberto Rodríguez',   position: 'CB', rating: 74 },
      { name: 'Jean Deza',           position: 'CB', rating: 73 },
      { name: 'César Huanca',        position: 'LB', rating: 72 },
      { name: 'Raziel García',       position: 'CM', rating: 75 },
      { name: 'Joao Contreras',      position: 'CM', rating: 73 },
      { name: 'Christian Ramos',     position: 'DM', rating: 74 },
      { name: 'Aldair Fuentes',      position: 'RW', rating: 74 },
      { name: 'Jorge Cazulo',        position: 'ST', rating: 74 },
      { name: 'Reimond Manco',       position: 'LW', rating: 74 },
      { name: 'Carlos Cáceda',       position: 'GK', rating: 71 },
      { name: 'Francis Ortiz',       position: 'CB', rating: 71 },
      { name: 'Dany Flores',         position: 'CM', rating: 72 },
      { name: 'Tony Urbano',         position: 'ST', rating: 73 },
    ],
    source: 'Transfermarkt — Cusco FC (2025/2026)', teamLabel: 'Cusco FC (2025–26)',
  },
  {
    slug: 'independiente-medellin', name: 'Deportivo Independiente Medellín', group: '🌎 América del Sur',
    ratings: { attack: 79, midfield: 78, defense: 77, goalkeeping: 77 },
    formation: '4-2-3-1',
    players: [
      { name: 'Andrés Mosquera Marmolejo', position: 'GK', rating: 78 },
      { name: 'Pablo Rojas',          position: 'CB', rating: 78 },
      { name: 'Jesús Murillo',        position: 'CB', rating: 79 },
      { name: 'Yulian Gómez',         position: 'RB', rating: 77 },
      { name: 'Yeferson Rodallega',   position: 'LB', rating: 76 },
      { name: 'Andrés Cadavid',       position: 'DM', rating: 78 },
      { name: 'Javier Reina',         position: 'DM', rating: 77 },
      { name: 'Daniel Torres',        position: 'AM', rating: 80 },
      { name: 'Luciano Pons',         position: 'RW', rating: 79 },
      { name: 'Ryan Lamont',          position: 'LW', rating: 78 },
      { name: 'Dorlan Pabón',         position: 'ST', rating: 80 },
      { name: 'Harlen Castillo',      position: 'GK', rating: 73 },
      { name: 'Jhon Velásquez',       position: 'CB', rating: 75 },
      { name: 'Baldomero Perlaza',    position: 'CM', rating: 76 },
      { name: 'Adrián Arregui',       position: 'ST', rating: 77 },
    ],
    source: 'Transfermarkt — Independiente Medellín (2025/2026)', teamLabel: 'Ind. Medellín (2025–26)',
  },
  {
    slug: 'coquimbo-unido', name: 'Coquimbo Unido', group: '🌎 América del Sur',
    ratings: { attack: 75, midfield: 74, defense: 73, goalkeeping: 72 },
    formation: '4-4-2',
    players: [
      { name: 'Martín Parra',        position: 'GK', rating: 73 },
      { name: 'Gabriel Suazo',       position: 'LB', rating: 76 },
      { name: 'Ángel González',      position: 'CB', rating: 74 },
      { name: 'Matías Muñoz',        position: 'CB', rating: 73 },
      { name: 'Brian Kalter',        position: 'RB', rating: 73 },
      { name: 'Leandro Vásquez',     position: 'CM', rating: 75 },
      { name: 'Pablo Solari',        position: 'CM', rating: 74 },
      { name: 'Germán Lanaro',       position: 'DM', rating: 73 },
      { name: 'Ignacio Carreño',     position: 'RW', rating: 74 },
      { name: 'Agustín Farías',      position: 'ST', rating: 76 },
      { name: 'Rodrigo Holgado',     position: 'LW', rating: 74 },
      { name: 'Ariel Cólzera',       position: 'GK', rating: 70 },
      { name: 'Felipe Gutiérrez',    position: 'CB', rating: 72 },
      { name: 'Rodrigo Mora',        position: 'AM', rating: 75 },
      { name: 'Máximo Núñez',        position: 'ST', rating: 75 },
    ],
    source: 'Transfermarkt — Coquimbo Unido (2025/2026)', teamLabel: 'Coquimbo Unido (2025–26)',
  },
  {
    slug: 'deportes-tolima', name: 'Deportes Tolima', group: '🌎 América del Sur',
    ratings: { attack: 77, midfield: 76, defense: 75, goalkeeping: 75 },
    formation: '4-3-3',
    players: [
      { name: 'Álvaro Montero',      position: 'GK', rating: 76 },
      { name: 'Juan García',         position: 'RB', rating: 75 },
      { name: 'Ánderson Plata',      position: 'CB', rating: 76 },
      { name: 'Julián Quiñones',     position: 'CB', rating: 75 },
      { name: 'Deinner Quiñones',    position: 'LB', rating: 75 },
      { name: 'Yeison Gordillo',     position: 'DM', rating: 77 },
      { name: 'Juan Guillermo Cuadrado', position: 'CM', rating: 79 },
      { name: 'Brayan Angulo',       position: 'CM', rating: 76 },
      { name: 'Jader Obrian',        position: 'RW', rating: 77 },
      { name: 'Dayro Moreno',        position: 'ST', rating: 78 },
      { name: 'Larry Angulo',        position: 'LW', rating: 76 },
      { name: 'Harold Rivera',       position: 'GK', rating: 72 },
      { name: 'Marcelino Carreazo',  position: 'CB', rating: 73 },
      { name: 'Leonardo Castro',     position: 'AM', rating: 76 },
      { name: 'Rafael Robayo',       position: 'ST', rating: 76 },
    ],
    source: 'Transfermarkt — Deportes Tolima (2025/2026)', teamLabel: 'Deportes Tolima (2025–26)',
  },
  {
    slug: 'independiente-santa-fe', name: 'Independiente Santa Fe', group: '🌎 América del Sur',
    ratings: { attack: 78, midfield: 77, defense: 76, goalkeeping: 75 },
    formation: '4-2-3-1',
    players: [
      { name: 'Leandro Castellanos', position: 'GK', rating: 76 },
      { name: 'Maicol Balanta',      position: 'CB', rating: 77 },
      { name: 'Jhon Lucumí',         position: 'CB', rating: 78 },
      { name: 'Santiago Montoya',    position: 'RB', rating: 76 },
      { name: 'Juan Camilo Salcedo', position: 'LB', rating: 75 },
      { name: 'Héctor Urrego',       position: 'DM', rating: 77 },
      { name: 'Gonzalo Castellani',  position: 'DM', rating: 76 },
      { name: 'Hugo Rodallega',      position: 'AM', rating: 79 },
      { name: 'Neyder Lozano',       position: 'RW', rating: 77 },
      { name: 'Edison Toloza',       position: 'LW', rating: 77 },
      { name: 'Luis Díaz',           position: 'ST', rating: 79 },
      { name: 'Gerardo Ortiz',       position: 'GK', rating: 72 },
      { name: 'William Tesillo',     position: 'CB', rating: 75 },
      { name: 'Kelvin Osorio',       position: 'CM', rating: 76 },
      { name: 'Carlos Rivas',        position: 'ST', rating: 76 },
    ],
    source: 'Transfermarkt — Independiente Santa Fe (2025/2026)', teamLabel: 'Ind. Santa Fe (2025–26)',
  },
  {
    slug: 'junior-barranquilla', name: 'Atlético Junior', group: '🌎 América del Sur',
    ratings: { attack: 80, midfield: 79, defense: 78, goalkeeping: 77 },
    formation: '4-3-3',
    players: [
      { name: 'Sebastián Viera',     position: 'GK', rating: 78 },
      { name: 'Mariano Barbieri',    position: 'CB', rating: 78 },
      { name: 'Jorge Arias',         position: 'CB', rating: 77 },
      { name: 'Walmer Pacheco',      position: 'RB', rating: 77 },
      { name: 'Déinner Quiñones',    position: 'LB', rating: 76 },
      { name: 'Edwuin Cetré',        position: 'DM', rating: 79 },
      { name: 'James Rodríguez',     position: 'CM', rating: 84 },
      { name: 'Carlos Bacca',        position: 'CM', rating: 80 },
      { name: 'Stiven Barreiro',     position: 'RW', rating: 79 },
      { name: 'Miguel Ángel Borja',  position: 'ST', rating: 82 },
      { name: 'Marco Pérez',         position: 'LW', rating: 80 },
      { name: 'Éver Meza',           position: 'GK', rating: 74 },
      { name: 'Gerard Moreno',       position: 'CB', rating: 75 },
      { name: 'Freddy Hinestroza',   position: 'CM', rating: 78 },
      { name: 'Carmelo Valencia',    position: 'ST', rating: 78 },
    ],
    source: 'Transfermarkt — Junior Barranquilla (2025/2026)', teamLabel: 'Junior (2025–26)',
  },
  {
    slug: 'cerro-porteno', name: 'Club Cerro Porteño', group: '🌎 América del Sur',
    ratings: { attack: 80, midfield: 79, defense: 78, goalkeeping: 77 },
    formation: '4-3-3',
    players: [
      { name: 'Jean-Claude Ndondele', position: 'GK', rating: 77 },
      { name: 'Blas Riveros',        position: 'LB', rating: 80 },
      { name: 'Lorenzo Melgarejo',   position: 'CB', rating: 78 },
      { name: 'Fabián Balbuena',     position: 'CB', rating: 80 },
      { name: 'Oscar Romero',        position: 'RB', rating: 78 },
      { name: 'Rodrigo Rojas',       position: 'DM', rating: 79 },
      { name: 'Gastón Olveira',      position: 'CM', rating: 78 },
      { name: 'Ángel Cardozo',       position: 'CM', rating: 78 },
      { name: 'Marcos Cáceres',      position: 'RW', rating: 79 },
      { name: 'Diego Gómez',         position: 'ST', rating: 81 },
      { name: 'Hernán González',     position: 'LW', rating: 80 },
      { name: 'Rodrigo Muñoz',       position: 'GK', rating: 75 },
      { name: 'Robert Morales',      position: 'CB', rating: 75 },
      { name: 'Nelson Haedo Valdez', position: 'AM', rating: 76 },
      { name: 'Víctor Bernay',       position: 'ST', rating: 77 },
    ],
    source: 'Transfermarkt — Cerro Porteño (2025/2026)', teamLabel: 'Cerro Porteño (2025–26)',
  },
  {
    slug: 'libertad', name: 'Club Libertad', group: '🌎 América del Sur',
    ratings: { attack: 79, midfield: 78, defense: 77, goalkeeping: 76 },
    formation: '4-3-3',
    players: [
      { name: 'Justo Villar',        position: 'GK', rating: 77 },
      { name: 'Iván Torres',         position: 'CB', rating: 78 },
      { name: 'Diego Gómez',         position: 'CB', rating: 77 },
      { name: 'Gustavo Gómez',       position: 'RB', rating: 82 },
      { name: 'Rodrigo Valizuela',   position: 'LB', rating: 76 },
      { name: 'Mathías Villasanti',  position: 'DM', rating: 79 },
      { name: 'Rodrigo Rojas',       position: 'CM', rating: 78 },
      { name: 'Miguel Almirón',      position: 'CM', rating: 82 },
      { name: 'Pablo Velázquez',     position: 'RW', rating: 78 },
      { name: 'Roque Santa Cruz',    position: 'ST', rating: 79 },
      { name: 'Santiago Arzamendia', position: 'LW', rating: 79 },
      { name: 'Vladimir Muñoz',      position: 'GK', rating: 73 },
      { name: 'Junior Alonso',       position: 'CB', rating: 77 },
      { name: 'Gastón Giménez',      position: 'CM', rating: 77 },
      { name: 'Óscar Cardozo',       position: 'ST', rating: 77 },
    ],
    source: 'Transfermarkt — Club Libertad (2025/2026)', teamLabel: 'Libertad (2025–26)',
  },
  {
    slug: 'universidad-catholica-chile', name: 'Club Deportivo Universidad Católica', group: '🌎 América del Sur',
    ratings: { attack: 80, midfield: 79, defense: 78, goalkeeping: 77 },
    formation: '4-3-3',
    players: [
      { name: 'Ariel Holan',         position: 'GK', rating: 77 },
      { name: 'Valber Huerta',       position: 'GK', rating: 77 },
      { name: 'Germán Lanaro',       position: 'CB', rating: 78 },
      { name: 'Ariel Martínez',      position: 'CB', rating: 78 },
      { name: 'Patricio Rubio',      position: 'RB', rating: 77 },
      { name: 'Sebastián Galani',    position: 'LB', rating: 76 },
      { name: 'Diego Valencia',      position: 'DM', rating: 79 },
      { name: 'José Pedro Fuenzalida',position: 'CM', rating: 81 },
      { name: 'Gabriel Castellón',   position: 'CM', rating: 78 },
      { name: 'Edson Puch',          position: 'RW', rating: 80 },
      { name: 'Fernando Zampedri',   position: 'ST', rating: 82 },
      { name: 'Cristián Álvarez',    position: 'LW', rating: 79 },
      { name: 'Arturo Vidal',        position: 'CM', rating: 83 },
      { name: 'Ignacio Saavedra',    position: 'CB', rating: 75 },
      { name: 'Felipe Gutiérrez',    position: 'AM', rating: 79 },
    ],
    source: 'Transfermarkt — U. Católica Chile (2025/2026)', teamLabel: 'U. Católica (2025–26)',
  },
  {
    slug: 'deportivo-la-guaira', name: 'Caracas FC / Deportivo La Guaira', group: '🌎 América del Sur',
    ratings: { attack: 74, midfield: 73, defense: 72, goalkeeping: 72 },
    formation: '4-4-2',
    players: [
      { name: 'Rafael Romo',         position: 'GK', rating: 73 },
      { name: 'Jhon González',       position: 'CB', rating: 73 },
      { name: 'Michael Morantes',    position: 'CB', rating: 72 },
      { name: 'Yohandry Orozco',     position: 'RB', rating: 73 },
      { name: 'Kervin Andrade',      position: 'LB', rating: 72 },
      { name: 'Arquímedes Figuera',  position: 'CM', rating: 74 },
      { name: 'Moisés Navarro',      position: 'CM', rating: 73 },
      { name: 'Sandro Merino',       position: 'DM', rating: 72 },
      { name: 'Alejandro Cichero',   position: 'RW', rating: 73 },
      { name: 'Daniel Morales',      position: 'ST', rating: 75 },
      { name: 'Salomón Rondón',      position: 'ST', rating: 76 },
      { name: 'Alexis Blanco',       position: 'GK', rating: 70 },
      { name: 'Juan Arango',         position: 'LW', rating: 73 },
      { name: 'Josef Martínez',      position: 'ST', rating: 77 },
    ],
    source: 'Transfermarkt — Deportivo La Guaira (2025/2026)', teamLabel: 'Dep. La Guaira (2025–26)',
  },
  {
    slug: 'universidad-central-vzla', name: 'Universidad Central de Venezuela', group: '🌎 América del Sur',
    ratings: { attack: 73, midfield: 72, defense: 71, goalkeeping: 71 },
    formation: '4-4-2',
    players: [
      { name: 'Daniel Santander',    position: 'GK', rating: 71 },
      { name: 'Fernando Aristeguieta',position: 'CB', rating: 72 },
      { name: 'Jhon Chancellor',     position: 'CB', rating: 73 },
      { name: 'Yohandry Orozco',     position: 'RB', rating: 72 },
      { name: 'Víctor García',       position: 'LB', rating: 71 },
      { name: 'Edson Castillo',      position: 'DM', rating: 74 },
      { name: 'Eric Ramírez',        position: 'CM', rating: 73 },
      { name: 'Rómulo Otero',        position: 'AM', rating: 75 },
      { name: 'Alejandro Guerra',    position: 'RW', rating: 73 },
      { name: 'Adalberto Peñaranda', position: 'ST', rating: 74 },
      { name: 'Nicolás Benedetti',   position: 'LW', rating: 73 },
      { name: 'Carlos Vargas',       position: 'GK', rating: 69 },
      { name: 'Luis Chávez',         position: 'CB', rating: 71 },
      { name: 'Jan Hurtado',         position: 'CM', rating: 73 },
      { name: 'Jhon Murillo',        position: 'ST', rating: 73 },
    ],
    source: 'Transfermarkt — Universidad Central VZL (2025/2026)', teamLabel: 'Univ. Central (2025–26)',
  },
  {
    slug: 'always-ready', name: 'Club Always Ready', group: '🌎 América del Sur',
    ratings: { attack: 74, midfield: 73, defense: 72, goalkeeping: 72 },
    formation: '4-4-2',
    players: [
      { name: 'Rubén Cordano',       position: 'GK', rating: 72 },
      { name: 'Roberto Carlos Fernández', position: 'CB', rating: 73 },
      { name: 'Alejandro Chumacero', position: 'CB', rating: 72 },
      { name: 'Jaiber Jiménez',      position: 'RB', rating: 72 },
      { name: 'Danny Bejarano',      position: 'LB', rating: 71 },
      { name: 'Leonel Morales',      position: 'CM', rating: 74 },
      { name: 'Michael Hoyos',       position: 'CM', rating: 75 },
      { name: 'Julián Álvarez Jr.',  position: 'DM', rating: 73 },
      { name: 'Chumacero Alejandro', position: 'RW', rating: 73 },
      { name: 'Rodrigo Ramallo',     position: 'ST', rating: 75 },
      { name: 'Sandro Vaca',         position: 'LW', rating: 73 },
      { name: 'Jorge Michel',        position: 'GK', rating: 70 },
      { name: 'Pablo Escobar',       position: 'CB', rating: 71 },
      { name: 'Ariel Martins',       position: 'CM', rating: 72 },
      { name: 'Nixon Quispe',        position: 'ST', rating: 73 },
    ],
    source: 'Transfermarkt — Always Ready (2025/2026)', teamLabel: 'Always Ready (2025–26)',
  },
  {
    slug: 'independiente-rivadavia', name: 'Club Atlético Independiente Rivadavia', group: '🌎 América del Sur',
    ratings: { attack: 76, midfield: 75, defense: 74, goalkeeping: 73 },
    formation: '4-4-2',
    players: [
      { name: 'Facundo Bonelli',     position: 'GK', rating: 74 },
      { name: 'Marco Di Césare',     position: 'CB', rating: 75 },
      { name: 'Cristián Ortiz',      position: 'CB', rating: 74 },
      { name: 'Lucas Morales',       position: 'RB', rating: 74 },
      { name: 'Franco Andrada',      position: 'LB', rating: 73 },
      { name: 'Maximiliano Ortiz',   position: 'DM', rating: 75 },
      { name: 'Braian Salvareschi',  position: 'CM', rating: 75 },
      { name: 'Gerardo Torales',     position: 'CM', rating: 74 },
      { name: 'Elías Gómez',         position: 'RW', rating: 76 },
      { name: 'Rodrigo Brusco',      position: 'ST', rating: 77 },
      { name: 'Bruno Sepúlveda',     position: 'LW', rating: 75 },
      { name: 'Sebastián Ramírez',   position: 'GK', rating: 71 },
      { name: 'Jonatan Gómez',       position: 'CB', rating: 72 },
      { name: 'Rodrigo Aliendro',    position: 'AM', rating: 76 },
      { name: 'Jean Franco Ramírez', position: 'ST', rating: 74 },
    ],
    source: 'Transfermarkt — Ind. Rivadavia (2025/2026)', teamLabel: 'Ind. Rivadavia (2025–26)',
  },
];

let created = 0;
for (const t of TEAMS) {
  const file = path.join(SQUADS_DIR, t.slug + '.json');
  if (fs.existsSync(file)) {
    console.log(`⏭  ${t.slug} — already exists`);
    continue;
  }
  const squad = {
    name: t.name,
    slug: t.slug,
    group: t.group,
    badgeLocalPath: `/img/badges/${t.slug}.png`,
    seasons: {
      '2025': {
        formation: t.formation,
        players:   t.players,
        ratings:   t.ratings,
        source:    t.source,
        teamLabel: t.teamLabel,
      }
    }
  };
  fs.writeFileSync(file, JSON.stringify(squad, null, 2));
  console.log(`✅ Created ${t.slug}.json`);
  created++;
}
console.log(`\nDone — created ${created} squad files`);
