# Auto-generated by UltraKibanaDownloader — base preset: Custom
# Edit conf_all.py to change the preset definitions.
import sys, importlib, types as _types
_base = importlib.import_module('conf_all').CONFIGS.get('Custom', {})
services   = [
    "cuxscored",
    "cuxsdialerd",
    "cuxs-situationd",
    "cuxs-rengined"
]
tags       = _base.get('tags', [])
listTagged = _base.get('listTagged', [])
listFiltered = _base.get('listFiltered', [])
