#UltraKibanaDownloader user settings
#Thu Mar 12 10:19:22 CET 2026
logsPath=C\:\\Users\\victor.vega\\OneDrive - Verisure\\Documents\\Workspace\\elasticlogana-master@4f909f66e7a\\elasticlogana-master@4f909f66e7a\\UltraKibanaDownloader_V4.0\\UltraKibanaDownloader\\logs
searchDirection=Find Previous/Next
